### ISSUE TITLE
Run in Browser

### ISSUE THREAD

**Issue by SaadBazaz** [mifi/lossless-cut#1022]
Hey there,
There is potential of expanding this application so it can run in the browser, and then using WASM or webservers the FFMPEG part can be handled.

Is there a way the web part can be safely separated from the Electron part, so it can be easily deployed to either platform (Electron vs Web) when a dev wishes?

**Comment by mifi** [comment]
Not really, but maybe something like this:

1. Rewrite lossless-cut to a (virtual) client-server model which is something I think has to be on done sooner or later due to electron recommending nodeIntegration be disabled and contextIsolation be used https://www.electronjs.org/docs/latest/tutorial/security - this would include eliminating all `window.require` calls and all `electron.remote.require`, however it's a quite big task because of the new APIs being severely lacking compared to nodeIntegration. (e.g. I'm not sure if streams, buffers, errors, complex objects, functions etc can be passed across the bridge). This touches on almost all code
2. handle all native modules/libraries: `trash`, `electron`, dialogs, fs, ffmeg, ffprobe
- ???

**Comment by SaadBazaz** [comment]
I think that would be a good way to future-proof the project as well, i.e. decoupling as much of it as possible from Electron. 

I can try with this roadmap you've described, probably the first step would be to at least comment out the electron functionality and hope it at least renders on the browser (even if it's an error)

**Comment by mifi** [comment]
If you like you can give it a try, good luck! Maybe you will have to make compromises that I cannot accept in terms of keeping the original app functionality for existing users, but then worst case it would end up as a fork

**Comment by mifi** [comment]
I'll close this because nothing more actionable for me here (i'm not going to implement this any time soon)

**Comment by Joshfindit** [comment]
Adding this here: With video file sizes constantly increasing, there's a really interesting use case for a web version:

Send video files over the LAN to a central server (for example using your other project ezshare), then edit from any device and export clips that can be downloaded. This would enable a lossless workflow that can be done entirely on a phone.

**Comment by mifi** [comment]
Although LosslessCut won't work in the browser any time soon, I found these amazing (and free!) web based projects for editing/converting videos in the browser:
- https://www.remotion.dev/convert
- https://wide.video/

**Comment by nikitazep** [comment]
I've currently implemented remote video editing on the web side via outlyernet/losslesscut docker

**Comment by mifi** [comment]
> I've currently implemented remote video editing on the web side via outlyernet/losslesscut docker

feel free to share your code & progress here :)
