### ISSUE TITLE
.exe & .zip both are portable classify them as such!

### ISSUE THREAD

**Issue by Droyk** [mifi/lossless-cut#1072]
Many times my brain just pauses and tries to understand the d/f's b/w the two &  it happens every damn time! 
which one is better? what are the diff's b/w the two?
which is one is for me?

since in your app case both are portable, just the `.exe` is compressed & the `.zip` one is uncompressed. if the user chooses .exe it will take some seconds to start the application and the .zip case needs to be extracted first but since it's an uncompressed version it will start immediately.

I think it would be better for everyone to mention the above differences (maybe with more clarity!) on the release page!
Thank you @mifi for continuously providing the time to maintain the app & to provide the requested features!
made my life a bit easier!

**Comment by mifi** [comment]
Thanks! That’s a good idea. I will update the readme

**Comment by mifi** [comment]
unfortunately the release page it's not possible to mention, but i added to the readme.

**Comment by Droyk** [comment]
how .exe is a self-extracting? it doesn't seem to extract anything on my system
does it extracts in the temp. folders?

is there is any reason to not do it like this?  
![image](https://user-images.githubusercontent.com/15848350/158032094-22d081ad-972f-47b3-a893-9d38b35b3367.png)

Of course with better words to differentiate b/w the two so users can understand easily which one suits their needs better?

**Comment by mifi** [comment]
> does it extracts in the temp. folders?

yes AFAIK it extracts to a temporary folder every time you run it. that's why it takes longer to start up.

Actually when I think about it, I don't really see much benefit of the .exe version (electron-builder calls it the `portable` target). Drawbacks:
- It's not really portable because it extracts itself every time to a system path and stores user settings in the appdata folder #645
- It seems to be mostly causing problems (e.g. on startup, not finding ffmpeg.exe in the temp folderr) #935 #849

So I think I will try to remove the exe variant in the next version and see if there are any objections (if there are good arguments for it I can put it back).

I will also try to use 7zip instead of zip for the windows download, because zip compression is not that great, leading to large downloads.

See also
- #935
- #849
- https://github.com/electron-userland/electron-builder/issues/1612
- https://github.com/electron-userland/electron-builder/issues/3799

**Comment by Dragodraki** [comment]
Hi there. In my opinion the self-executable was just great. For all apps that are not as lets say larger than 500MB or need persistence for some reason I am fond of the SFX-Archive format. I already asked to get them back here (https://github.com/mifi/lossless-cut/issues/2055).

Of course they have its disadvaantages. But here are my thoughts related to them:
- As for the main reason, the time delay to extract, I can say, everyday you use Windows 10 or higher you suffer from apps loading significantly slower than back in the day in Windows XP/7/8 - even notepad, cmd, control, settings, etc.
- SFX-Archives needs more disk space. But does it really matter? Back in the 90's when every byte counted and CD's/floppys had more space than HDD's (not talking about the price) it may had been a waste, but today? SSD's and NVMe's come not less than 256GB (tend is 2TB) and Windows itself eats about 30GB away. It seems rather ridiculous to me to worry about 150MB that is written to temp and auto-deleted on end.
- That browsers block executables is an arguing fact we cannot change so easily. Everyone has to decide theemselves whether you let a browser tell you what to do or not
- But my main argument pro SFX-archive is that I don't like loose library files lying around in uncountable folders and subfolders. I think: Either using a real setup wwith permanent installation and forgetting about the dependency files or using a single-file portable. This way accidentially changes to the program can be prevented in a effective way and the download folder is kept clean.

I hope, mifi will consider about providing the portable version for LossLessCut in the next versions again.
