### ISSUE TITLE
app package size on macos

### ISSUE THREAD

**Issue by davxiao** [mifi/lossless-cut#108]
Hi there, 

Just wondering if there is a reason that the file size of Macos package is actually over 200 MB... Thanks

**Comment by mifi** [comment]
Hi. If you look into the App file, ffmpeg and ffprobe take 130MB, electron takes 120mb.
im not sure if it's possible to compress mac apps or electron apps. If i ZIP it, it becomes 100MB, so it could be an improvement. If anyone wants to help I'm happy to consider a change.

**Comment by allenfoxtc** [comment]
> Hi. If you look into the App file, ffmpeg and ffprobe take 130MB, electron takes 120mb.
> im not sure if it's possible to compress mac apps or electron apps. If i ZIP it, it becomes 100MB, so it could be an improvement. If anyone wants to help I'm happy to consider a change.

you can try webpack both main part(main process) and renderer part(jsx js html css...), webpack will pack all needed node_modules into one js file, so we can exclude node_modules from build.

then use system ffmpeg & ffprobe instead of static one. those two commands probably share some common libs, so we can reduce both dependencies size and app size.

here is my change
package.json
`
{
  ... ,
  "main": "main.js",
  "scripts": {
    ... ,
    "webpack-main": "webpack --config webpack.main.additions.js",
    "webpack-renderer": "webpack --config webpack.renderer.additions.js",
    "webpack": "yarn webpack-main && yarn webpack-renderer",
    "dist": "yarn webpack && electron-builder -p never"
  },
  ... ,
  "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.8.4",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "babel-eslint": "^10.0.3",
    "babel-loader": "^8.0.0",
    "css-loader": "^3.4.2",
    "electron": "^8.0.0",
    "electron-builder": "^22.3.2",
    "electron-builder-notarize": "^1.1.2",
    "eslint": "^5.16.0 || ^6.1.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^1.7.0",
    "extract-loader": "^4.0.3",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "file-loader": "^5.1.0",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "spawn-sync": "^2.0.0",
    "svg2png": "^4.1.1",
    "terser-webpack-plugin": "^2.3.5",
    "url-loader": "^3.0.0",
    "webpack": "^4.41.6",
    "webpack-cli": "^3.3.11"
  },
  "dependencies": {
    ... ,
    "which": "^2.0.2"
  },
  ... ,
  "build": {
    "files": [
      "!node_modules/**/*",
      {
        "from": "build/main",
        "to": "",
        "filter": [
          "**/*"
        ]
      },
      {
        "from": "build/renderer",
        "to": "",
        "filter": [
          "**/*"
        ]
      }
    ],
    "asar": {
      "smartUnpack": false
    },
    "appId": "no.mifi.losslesscut",
    "artifactName": "${productName}-${os}.${ext}",
    "afterSign": "electron-builder-notarize",
    "mac": {
      "hardenedRuntime": true,
      "target": "dmg",
      "icon": "icon-build/app-512.png"
    },
    "win": {
      "target": [
        "portable",
        "zip"
      ],
      "icon": "icon-build/app-512.png"
    },
    "linux": {
      "icon": "icon-build/app-512.png",
      "target": [
        "tar.bz2",
        "AppImage",
        "snap"
      ]
    },
    ...
  }
}
`

webpack.main.additions.js
`
const webpack = require('webpack');
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  mode: 'production',
  devtool: false,
  target: 'electron-renderer', // using electron-main will get an error during Terser, it seems that Terser can not read Github.js, if. you want to use electron-main as target, try replace 'require("github-api")' with 'require("github-api/dist/GitHub.min");'
  entry: './src/index.js',
  output: {
    path: `${__dirname}/build/main`,
    filename: 'main.js',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
      },
    ],
  },
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        sourceMap: false,
      }),
    ],
  },
  plugins: [
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'production',
      PATH: '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',
    }),
  ],
  resolve: {
    extensions: ['.js'],
    modules: [`${__dirname}/src`, 'node_modules'],
  },
};
`

webpack.renderer.additions.js
`
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  mode: 'production',
  devtool: false,
  target: 'electron-renderer',
  entry: './src/index.html',
  output: {
    path: `${__dirname}/build/renderer`,
    publicPath: '',
    filename: 'renderer.js',
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract({
          loader: 'css-loader',
          options: {
            modules: true,
          },
        }),
      },
      {
        test: /\.html$/,
        loader: 'html-loader',
        options: {
          attrs: ['link:href', 'script:src'],
        },
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        query: {
          name: '[name].[ext]?[hash]',
        },
      },
      {
        test: /\.(png|otf|eot|svg|ttf|woff2?)(\?.*)?$/,
        loader: 'url-loader',
      },
    ],
  },
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        sourceMap: false,
      }),
    ],
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: '',
      templateContent: '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body><div id="app"></div></body></html>',
    }),
    new ExtractTextPlugin({
      filename: 'main.css',
      disable: false,
      allChunks: true,
    }),
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'production',
      PATH: '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',
    }),
  ],
  resolve: {
    extensions: ['.js', '.json', '.jsx', '.css', '.html'],
    modules: [`${__dirname}/src`, 'node_modules'],
  },
};
`

.babelrc
`
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": "commonjs",  // this is important, otherwise you will get module.export error while running in production mode
        "targets": {
          "electron": "8.0"
        },
        "useBuiltIns": "usage"
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    [
      "@babel/plugin-proposal-object-rest-spread",
      {
        "useBuiltIns": true
      }
    ]
  ]
}
`

src/index.html
`
...
<script src="./renderer.jsx"></script>
...
`

src/ffmpeg.js
`
...
const which = require('which');
...
function getPath(type) {
  return which.sync(type);
}
...
`
if you get any error like 'invalid assignment' during webpack, try remove all assignment of 'process.env.NODE_ENV'.

the final mac app is 173.5mb.


the next level is try to use sth else to replace electron without rewrite whole code. i'm currently interest in webview(https://github.com/zserge/webview).

**Comment by mifi** [comment]
Thanks for your suggestions. I'm not planning on using Webpack directly in this project. I'm gonna switch over to Create-react-app. hopefully it will reduce size

**Comment by opusforlife2** [comment]
> I will not remove ffmpeg from the bundle, because we don't know if the user has ffmpeg or not.

You could offer a zip with and without ffmpeg bundled.

Would the code have to be changed to look for the binary on the system? Or maybe you could prompt the user to locate the binaries themselves.

**Comment by mifi** [comment]
Sure, could possibly release two versions of each binary. Although it’s not something i’m going to prioritize. If someone with expertise on electron-builder wants to implement this i’m open to accept a PR, as long as it doesn’t require too much complicated logic/rewrite of the build system.

Implementing an option to use an external Ffmpeg instead of the bundled one should be an easy task however. But I indend for losslesscut to always bundle the latest version of ffmpeg, so im not sure how useful it would be.

**Comment by opusforlife2** [comment]
Oh. I missed it when you updated the ffmpeg version. Anyway, it would be good to have a ffmpeg-less version regardless, as ffmpeg is used across multiple software, such as youtube-dl. A user who has one binary of ffmpeg installed can then use it everywhere.

**Comment by mifi** [comment]
Yea I agree it would be optimal not to duplicate ffmpeg. But since most users don't have ffmpeg installed, I will need to bundle it.

**Comment by opusforlife2** [comment]
Agreed.

**Comment by mattack1** [comment]
While I understand the want for a smaller sized download, I sure would NOT want the user to have to "locate the binaries themselves".  Especially with a GUI app, IMO it should be fully-functional out the box (and/or download necessary pieces on first launch -- I know there are reasons why other binaries might not be actually bundled with an app).

**Comment by allenfoxtc** [comment]
> While I understand the want for a smaller sized download, I sure would NOT want the user to have to "locate the binaries themselves". Especially with a GUI app, IMO it should be fully-functional out the box (and/or download necessary pieces on first launch -- I know there are reasons why other binaries might not be actually bundled with an app).

Agreed. I'm currently using this app as a vnc docker container, so i want reduce the image size by using webpack and ffmpeg from apt repo.
