### ISSUE TITLE
Detect and prevent non-keyframe cutpoints.

### ISSUE THREAD

**Issue by jtagcat** [mifi/lossless-cut#1105]
> Note: cutpoints may be inaccurate

I cut from keyframe to keyframe, it should be fine (or not, am I wrong?). If I'm not, don't show the inaccuracy warning when cut does start from keyframe to keyframe.

As I'm working with h265 content, I can't trust the Smart Cut feature. It'd be nice to have a blocking warning on pressing the export button, that the cutpoints are not on keyframes.

**Comment by mifi** [comment]
the problem is that it's hard to determine whether the resulting cut will be accurate or not. it depends on a lot of factors and varies from file to file, hence one of the reasons why smart cut is considered experimental. I plan on improving the cutting so that it somehow snaps to keyframes in the future, but I don't think completely blocking exporting is the right way to do it. See previous discussions #330

**Comment by jtagcat** [comment]
Yeah, meanwhile I got smart cut functional, so it isn't much relevant anymore.

**Comment by mifi** [comment]
that's great!
