### ISSUE TITLE
Shortcut for deleting source

### ISSUE THREAD

**Issue by happyfilmmaker** [mifi/lossless-cut#114]
It would be nice if the delete source file feature had a keyboard shortcut like 'd' or 'delete'. It would make the app a lot better as I personally use the tool to trim files, and need to delete source for nearly all files I use.

**Comment by profucius** [comment]
Might be nice but of course with a keyboard shortcut for this you'd want a confirmation dialog in case of accidental presses, or an undo.

**Comment by mifi** [comment]
We already have a dialog, so yes we only need a keyboard shortcut. <kbd>del</kbd> has also been suggested (#87). I think `d` might be better because mac doesn't have <kbd>del</kbd>, and backspace is used for removing segments, so might be confusing with <kbd>del</kbd> deleting the source.
Vote 🚀 for <kbd>del</kbd> or 👀 for <kbd>d</kbd>

**Comment by mifi** [comment]
This is now implemented. Use <kbd>d</kbd>
