### ISSUE TITLE
Add to winget

### ISSUE THREAD

**Issue by Cyberavater** [mifi/lossless-cut#1279]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Hello, can you add this package to winget?

I've already opened an issue there, they're asking to sign the appx file.

https://github.com/microsoft/winget-pkgs/issues/72074#issuecomment-1227630108

**Comment by mifi** [comment]
Unfortunately I'm not going to work on signing the appx file, but if someone wants to submit a PR, you're welcome to do that. For more info see #337

**Comment by asilentdreamer** [comment]
I believe this issue should be re-opened as winget now supports installing portable apps that are distributed as an archive. Unfortunately it only supports zip archives right now and lossless cut is only distributed as 7z on windows.

**Comment by mifi** [comment]
hmm, can zipped unsigned exe files be added to winget? if so, then maybe we could add a post-build script to convert the 7z to zip and then auto upload it to winget. though it's not a priority for me to implement unfortunately.

**Comment by asilentdreamer** [comment]
Yes, winget doesn't have any issue with unsigned exes. It would be pretty easy to set it up using https://github.com/vedantmgoyal9/winget-releaser once there is a zip file in releases. But yeah, I understand that this is a low priority issue.

**Comment by mifi** [comment]
so is this comment incorrect? https://github.com/microsoft/winget-pkgs/issues/72074#issuecomment-1227630108

**Comment by asilentdreamer** [comment]
When that comment was made 2 years ago, winget didn't support zip files or portable apps. Now it does and can install apps from a zip archive or standalone exes just like scoop does.

So you don't need to bother with appx now but that comment is accurate. To my knowledge if you use an appx file , it does need to be signed.

**Comment by mifi** [comment]
ok, thanks for clarifying

**Comment by mifi** [comment]
Personally I don't have any incentive to publish and maintain a separate winget version of losslesscut. If people want auto updates and support my work, they can get get it from the MS Store (which I do maintain). Because the github version of losslesscut will notify people if it's outdated, I think it's gonna be hard for people to not notice after 4 years. if they don't want to upgrade, that's also fine. So to summarize: maintaining a winget package adds extra work for me, and it's a slippery slope, because once I accept one such request, there will surely be more requests. However if anyone else wants to do the work+maintenance and package losslesscut and publish it on winget, that is totally fine with me (it's GPLv2 after all). Just like someone (not me) published it on [chocolatey](https://community.chocolatey.org/packages/lossless-cut) and [flathub](https://github.com/flathub/no.mifi.losslesscut).

**Comment by pyorot** [comment]
I think after researching winget some more, your position makes more sense. It moves like abandonware despite being only 4 years old. In my mind, winget should fill the niche of being the default OS-provided method for managing packages semi-automatically, similarly to apt in Linux, since it's first-party and based on the same design. If that were the case then I'd have more of a qualm with intentionally not supporting it to funnel money towards MS Store and I'd suggest something more akin to the "license" model I've seen with immich for example. Having to manually download installers is terrible but I think given the state of winget, the future is not yet now. Thanks for the explanation 🙇‍♂️.

You're probably right about it being hard to not notice a new version, but my 4-year-old version didn't have an update-available alert built into it haha.

**Comment by dlong500** [comment]
@mifi I'd urge you to reconsider supporting winget directly.  It absolutely has become the de facto CLI windows package manager, and the danger of allowing a third-party to release the package (such as [here](https://github.com/chrishuan9/LosslessCut-winget-rls)) is that you never know when a malicious package might get swapped for the real one.  Plenty of people are just going to install what's available on the winget registry, and while the users that do that are not your responsibility if something goes wrong it still could cause a mess that could be avoided if you directly added software to the winget registry yourself.

The beauty of winget is not having to deal with individual update checks and manual installs.  You can with one command update virtually all the software on a machine.  Other package managers like chocolatey/scoop were on the scene first, but I'd argue winget surpassed them in terms of features and supported software a couple years ago.

Not knocking the other guy who is packaging a release--he may be perfectly legit and just trying to help out.  But I'm not going to risk installing/updating from a third-party packager.  Supply-chain exploits are scary.

You could probably look at that guy's Github Action logic and just incorporate something similar to have things pretty automated on your end.  That would make things pretty maintenance free, but I understand there is always extra work involved in adding support for virtually anything.

**Comment by mifi** [comment]
The problem is that there are so many different OS'es, CPU architectures and package managers that people want me to support, and I don't have capacity to maintain all, so I've only prioritised a few popular ones that have built-in support in electron, in the hopes that users of other electron based apps will also have to deal with any issues or regressions that may arise, so I don't have to. I do recognise the issue of other people maintaining third party packages, so I will try to make it more clear that people will have to use those at their own risk and they are not maintained by me.
