### ISSUE TITLE
Help - how do I cut?

### ISSUE THREAD

**Issue by LeoLevosky** [mifi/lossless-cut#128]
The program says it is lossless cut but it seems to be "lossless keep" rather than cut, or am I missing something?

I want to cut out all the parts of the videos I don't want and keep what is left, but it seems as if I have to cut out the parts I want to keep and then merge the remaining videos. Is this correct? If so, why? It is counter intuitive. I use TS-Doctor and it works how I would expect it to. How can I get lossless-cut to behave this way?

**Comment by mifi** [comment]
Yeah, because prior to v2 it was only possible to do export of selected portions, that’s how it still works. So you can achieve the same thing, but in a different way. If you have any idea on how to visualize this in a backward compatible way please share. I’m thinking maybe we could show a trash icon on the sections that are not included.

**Comment by LeoLevosky** [comment]
If you have a look at TS-Doctor I think they do it well but their software only works on .TS files. There you highlight the part you want to delete in a similar way to yours but the bits you want to cut out show in red on the timeline. Then you save to a new file. See the screenshot 

![capture](https://user-images.githubusercontent.com/7292936/52731362-76c94a00-2fb5-11e9-937c-25d88fbae048.JPG)

**Comment by pkamb** [comment]
> Maybe counter-intuitively for some, cutting will remove the parts that of the video that are NOT selected. This is because in previous versions of LosslessCut there was no possibility to cut/merge multiple segments, but this was retrofitted later. Need to redesign the UI to make it more intuitive. See #128

IMO you should use the word "trim" instead of "cut". 

This is how QuickTime on the Mac refers to the tools. It even uses a very similar interface.

A "trim" indicates that the portion you select will be kept, and the excess bits on both sides cut away and discarded.

![Screen Shot 2019-09-17 at 1 31 56 AM](https://user-images.githubusercontent.com/342355/65025220-27505100-d8eb-11e9-9d16-39b3a80b2cbc.png)

**Comment by mifi** [comment]
have now improved UI in newest version and allow for discarding segments
