### ISSUE TITLE
Project File LLC should store File Location

### ISSUE THREAD

**Issue by defencedog** [mifi/lossless-cut#1385]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

The `.llc` file starts with:
```
{
  version: 1,
  mediaFileName: 'Danni - Net Video Girls.mp4',
  cutSegments: [
.
.
.
```

Can we add `mediaFileLocation` so that when loading the project file application loads media from this location

**Comment by mifi** [comment]
We could add a separate mediaFileLocation, but I'm not sure if loading the media from that location is the right thing to do, because the way it works now is that it will load the media file in the same directory as the llc file. If we load from an absolute  path `mediaFileLocation`, then if the user moves the file to a different folder, it breaks. What is the use case for this?

**Comment by mifi** [comment]
I see. I think that use case could be solved by sorting files by file type, so that all the project files are grouped together. But maybe also attempting to load files from an absolute path `mediaFileLocation` could be useful feature to some. It's the first time I heard this request so I can leave it open to see if there's more interest for this.

**Comment by mifi** [comment]
i put this in #371 - closing this issue
