### ISSUE TITLE
Proposed update not compatible with the used system

### ISSUE THREAD

**Issue by MacTerrassa** [mifi/lossless-cut#1386]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

I am using an iMac Intel Core 2 Duo (2007) with OS 10.11.6, it cannot be updated any further.
LosslessCut in its version 3.47.1 opens correctly, although I have not yet used it. But it warns of an available update without indicating more than its version 3.48.2 and nothing else. When I download the disk image, and open it, I see an application package with the prohibited sign on its icon, and when I double click it, it warns that it requires system 10.13. 
Shouldn't the program notify you that this update is not compatible with your system? It is one thing to indicate that it exists and that you cannot install it, but if it is offered without further ado, it is useless.
I've searched your website, and I don't see any indication about your requirements. Are they not important and have to be communicated to the users? I understand that these requirements change over time, and that they are forcing to upgrade to more modern systems, but the first step is to indicate them. And when they change, communicate it. And it's a good thing Lossless doesn't seem to update itself without prompting, as I do with other programs that you end up deleting from the drive simply because they update automatically without prompting, and you end up with something you can't use or open.
The operating system and hardware requirements should be the first indication of any program to its users. Even if it's just to avoid calls to support about the program not working, when it's simply designed for other systems. As it is not indicated, nobody knows and the fault is with the programmer, not with not meeting those minimums.
Regards

MacTerrassa

P.S. Message translated mechanically as I do not speak English, I apologize if I have not expressed myself correctly.

**Comment by mifi** [comment]
Hi!
LosslessCut is an open source project and I do my best to ensure a good user experience. However I do not test on old versions of operating systems before I release new versions. I agree that in an ideal world, losslesscut should not give you a notification about an updated version if your OS does not support that version, however I don’t think it’s worth it for me to spend time implementing such a function in the update notification feature, as there are so many other more important features to implement. **I think what I can do is to introduce a new setting to disable automatic update notifications**, how does that sound?

As for the reason why macos 10.13 is now required is because I upgraded Electron to version 21. electorn in built on Chromium which is Chrome’s engine. Looking at this page I can see that Chrome now requires macos 10.13 or newer, so that’s the reason why losslesscut also requires this:
https://support.google.com/chrome/a/answer/7100626?hl=en
