### ISSUE TITLE
Add the version number to future release assets

### ISSUE THREAD

**Issue by jbruchon** [mifi/lossless-cut#1404]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Whenever I download a LosslessCut release, I end up with the exact same file name as previous releases. To find out what version is contained within a downloaded release file or a "7-Zip -> Extract to xxx" folder, I have no choice but to either manually rename everything with the version number myself prior to use (which I do now, but am getting a bit tired of doing every time I upgrade) or to extract and run LosslessCut to determine its version.

It would be very helpful from a file management perspective to have the version number included in the file names of all release assets. For example: I'm downloading version 3.48.2 right now and the package is called `LosslessCut-win-x64.7z` but it should ideally be called `LosslessCut-3.48.2-win-x64.7z`.

Edit: I said "future" because I don't feel that it's necessary to do this for prior releases. It would be nice to have this moving forward.

**Comment by mifi** [comment]
The reason why I exclude the version number from the download, is because I want to be able to link directly to the latest version from the github readme, e.g.:

https://github.com/mifi/lossless-cut/releases/latest/download/LosslessCut-mac-x64.dmg

I don't know if there's any easy way to include version inside the file name and still always link to the latest version. Unfortunately there's so many other features to implement that I'm not going to spend any time on this, but if someone wants to, I'm open for PRs, as long as the fix is not too complex. Therefore I'll close this now.

**Comment by jbruchon** [comment]
My opinion is that the increased manageability of a versioned filename outweighs the value of direct linking to a generic name in the README. The most obvious solution is to link to https://github.com/mifi/lossless-cut/releases which will always have the latest published release at the top. The file names already identify the platform and packaging type.

If the concern is that the user won't understand the formats (which file to download for their platform) then a simple copy-paste boilerplate can be added to the bottom of each GitHub release's description. If a user is downloading releases from GitHub they're very likely to be able to at least figure out which file works with the platform they're currently using without extra help.

**Comment by jbruchon** [comment]
I also just made another observation that's relevant if you link to releases directly but is also useful for those who happen to go there on their own. The latest release has "Beta!" prominently in the title but is marked as a production release. It needs to be edited and the checkbox for "this is a pre-release" should be checked.

**Comment by mifi** [comment]
I prefer not to send people to the releases page, because I had so many people create issues or contact me because they don't know which download to click, or they try to download LosslessCut-mac-universal.pkg or LosslessCut-win-x64.appx only to find out they don't work after downloading (because they are for app store distribution).

> If the concern is that the user won't understand the formats (which file to download for their platform) then a simple copy-paste boilerplate can be added to the bottom of each GitHub release's description. If a user is downloading releases from GitHub they're very likely to be able to at least figure out which file works with the platform they're currently using without extra help.

If it's possible to automate this in a simple way I could be open for it, but I have an automated build process and I don't want it to involve any more manual steps

> The latest release has "Beta!" prominently in the title but is marked as a production release. It needs to be edited and the checkbox for "this is a pre-release" should be checked

Yea it's not technically correct, but I want people to see the release and test it even if it's a pre-release (the app currently only notifies about a new non-prerelease versions)
