### ISSUE TITLE
Add mpdecimate feature to remove similar frames

### ISSUE THREAD

**Issue by rudolphos** [mifi/lossless-cut#1448]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

[mpdecimate](http://underpop.online.fr/f/ffmpeg/help/mpdecimate.htm.gz) is an ffmpeg feature, which losslessly can remove frames that are the same. This is useful for videos which mostly contain a presentation of still frames.

Sometimes this can cause keyframe issues where resulting video doesn't start and you have to scrub manually further for it to play. I think here can come handy the already existing lossless-cut feature which re-renders some parts of the video to avoid keyframe issues.

This is a small excerpt from the PowerShell script I use:
`ffmpeg -i $var.FullName -vf mpdecimate -fps_mode vfr -acodec copy $($path+'\'+$tempName)`

**Comment by mifi** [comment]
Hi. I don't think this is a lossless operation. Meaning that in order to use mpdecimate, you would have to re-encode the video. This means it's not really part of losslesscut's main feature set. As for re-encoding parts of the video to in order to call mpdecimate, I'm not sure exactly what that will solve. Do you have an example reproducible case where mpdecimate would solve a problem?
