### ISSUE TITLE
Improve preview playback

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#1584]
For me this shortcut just starts playing the current segment from the beginning.

Maybe I didn't explain clear enough, but I would need it to work this way:

I have: (The || is playhead)

<-------SEG1----||---> <----- EMPTY space -----> <-------SEG2-------> 

Currently, when pressing rainbow button, or "Loop beginning and end of current segment", it goes to the beginning of SEG1, plays whole SEG1 and jumps over EMPTY space and goes to SEG2 (as expected).

But I need a shortcut (or option to make play/pause work this way), that would start playing where the "||" (playhead) is (not particularly from end, but wherever I put it and start from that position), and jump to the SEG2 (like the rainbow button does). 

Most importantly, that it wouldn't start from the beginning of current segment, but start from wherever the playhead currently is.

Thanks for your replies! 🙂

_Originally posted by @rRobis in https://github.com/mifi/lossless-cut/discussions/1581#discussioncomment-5714375_

**Comment by slrslr** [comment]
> For me this shortcut just starts playing the current segment from the beginning.

For me 3.54.0 Linux AppImage does otherwise. It preview from first segment and can not be fast forwarded needing to long wait until it end up being at positions of interest.

Steps to reproduce: I doubleclick last segment in the right sidebar (list of segments) to jump to it, click preview button.
[Video showing how i do it](https://drive.proton.me/urls/MK4MGHQ3VW#5ozvp8EzWlc9).
3.54.0 Linux AppImage ([Bug report detail](https://bin.disroot.org/?130b52e7455c952a#Etx5bMx6bwn7RdB8ZxVnNRrEt5az3M3vzVTo6cVYxNR4))

**Comment by rRobis** [comment]
Yes you're right, i tested only the first segment, that's why it seemed that it starts from current one. I tried, and it behave just like you showed.

**Comment by mifi** [comment]
yes. this is how the feature was implemented in v1 (working as intented). but I agree it makes more sense to start from the current segment so it will be implemented as a future enhancement

**Comment by rRobis** [comment]
> 

Do you mean, it will start from the beginning of the current segment, or from the play head position?

**Comment by mifi** [comment]
it will start from the first segment (segment number 1) according to the right side segment list
