### ISSUE TITLE
GoPro Session5 Files are not be able to cut in 2.3.0

### ISSUE THREAD

**Issue by gotsila** [mifi/lossless-cut#173]
on cutting Gopro Session5 Files (+.mp4) it comes an error.

V2.2.0 is working. i am went back to V2.2.0

**Comment by mifi** [comment]
I think it uses h265 right? then you need to convert to friendly codec (slow) first

**Comment by gotsila** [comment]
Hy, it uses h.264 
Anyway it works all in the old Version. 
So i dont need the anoing „friendly codec“

Thx 

Gesendet mit meinem iPhone

Am 20.06.19 um 16:11 schrieb Mikael Finstad

**Comment by DerOrakel** [comment]
Same problem here, a little note 2.2.0 shows mov in the lower left 2.3.0 shows mp4.

**Comment by ericvaandering** [comment]
Same with Hero 4 files. However, 2.2.0 works fine.

**Comment by mifi** [comment]
Something wrong with the detection of file format. LosslessCut is using [file-type](https://www.npmjs.com/package/file-type) which changes alot recently, and this package was updated between 2.2.0 and 2.3.0 to fix another issue (#144) but I guess it introduced a new issue then.

I'm not quite sure how to handle this issue with MOV/MP4 because obviously ffmpeg seems to be a bit picky about the output format sometimes

**Comment by mifi** [comment]
I tested also with newest version of file-type and it is still detecting the file as mp4. will try to find a better way to detect

**Comment by mifi** [comment]
Have implemented the option to choose output format in the newest version.

**Comment by mifi** [comment]
Now in v3 this is fixed. The problem seems to be because ffmpeg is not able to correctly cut the extra data streams tmcd, fdsc and gpmd, and not able to save them into an mp4 file. Since gopro files are MP4, not MOV, detected format mp4 is the correct behavior. the old version was wrong showing MOV. See also #121
