### ISSUE TITLE
How to zero timecode?

### ISSUE THREAD

**Issue by asherber** [mifi/lossless-cut#174]
In pre-2.0 versions, when I extracted a segment of a video, the resulting clip started at timecode 0:00. This was good. 

In latest version 2.3.0, the extracted clip seems to retain the timecode from the original file.

Is this the expected behavior? If so, how can I get back the old behavior? Do I have to manually set a negative offset? It would be nice to have a quick option button to select which behavior is in effect.

**Comment by mifi** [comment]
can you try to only include primary streams? toggle "all" to "ps"

**Comment by asherber** [comment]
Yes, thanks, that does it. Maybe this could be pointed out in the Readme? And/or defaulted to `ps` so as to be consistent with previous behavior.

**Comment by mifi** [comment]
The reason I want to default to "all" is so that by default the operation is as lossless as possible, meabning that if the input has more than 2 streams, i want to include all streams in the output also, and not just discard everything else than the first audio/video stream. But this could be changed if many people think otherwise. I will add to readme
