### ISSUE TITLE
inconsistent ui elements

### ISSUE THREAD

**Issue by gouryellas** [mifi/lossless-cut#1776]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Love the program. Thanks for it.

Just a quick, somewhat nitpicky, thing - I use ahk to completely automate lossless. This relies on certain ui elements to have fixed locations. One example of inconsistency is with the export option for filename. If the video only has **1** cut segment, the filename box is rather complex. If the video has **more** than 1 cut segment, the filename box is completely different. See screenshots for examples.

I know you are busy, but if it is possible in the future to maintain consistency for things like this, it would be greatly appreciated. I have to re-code my massive script everytime a new release is out (if things have been changed or moved around). I understand this is unavoidable to some degree, especially with new features. Just asking for as much consistency as possible.

Thanks for your hard work.
![screen1](https://github.com/mifi/lossless-cut/assets/122081067/c8618fe5-f382-4a22-be19-ecb0d32b0471)
![screen2](https://github.com/mifi/lossless-cut/assets/122081067/9f72feeb-34da-45cf-9cca-cb103f766973)

**Comment by mifi** [comment]
Hi. This is because they are actually completely different things. the UI in your second screenshot is only shown if you have export mode set to "merge cuts". If you choose "separate files" you will see the UI from screenshot 1 **also for multiple files**. The reason why the output file name input is more complex, is because it allows customising the file names based on each segment's parameters like from/to time, segment name, tags etc. When you merge segments into a single segment, there are no such parameters, so it doesn't make sense to use that UI.

**Comment by mifi** [comment]
I believe nothing much I can do here, thanks.
