### ISSUE TITLE
[Request] Save project file

### ISSUE THREAD

**Issue by Visulth** [mifi/lossless-cut#181]
I really like your program and use it a lot.

Any chance a future build could save a file with the cuts/times/etc so it could reload your work (instead of being forced to leave the project open or finish all the cutting in one session)?

Sometimes I end up editing a rather large video and want to pick up working at a different time. 

Thanks for your work!

**Comment by mifi** [comment]
Hey! This is something that should be relatively trivial to implement, but I'm not sure if it's a common problem, I'll leave it for a little to see how many would want this feature.

**Comment by alsab200** [comment]
It is, very crucial to me.. Reasons? Long project; should I keep the program open? Why I should be forced to leave the computer on? Also, if I want to keep the records for the project?
Well, the number 1 competitor Avidemux which I've been using for years has it for years.. Why I am here? Because of the GUI, because I can modify the segments and export them seperately/individually.. 
Thanks very much in any case for such a great program; it's not easy to be considered as a rival to Avidemux, of course for "trimming only" projects..

**Comment by mifi** [comment]
auto save and load timestamps from CSV is now implemented in newest version along with many other new features!
