### ISSUE TITLE
Using Continuos SEG_Num in diffenret Files

### ISSUE THREAD

**Issue by vipergts** [mifi/lossless-cut#1846]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

When edit a file we can make segment and export files name on segments name by ${SEG_NUM}  
but when we include more files then the segment number shoud start 1

How about add function continuous Seg_num ?

like this  

A file -> 1,2,3 segment_number
B file -> 4,5,6 segment number   
C file -> 7,8,9 segment number 

If we merge all files (A,B,C) 
this problem will be solved 

However, it is very difficult and waste time  when we load many files or
load files with different types of codecs.

So just add function in export segment page right side 
following number before edit segment or can change number start what we want   

Thank you 

578

**Comment by mifi** [comment]
Hi. I think you can workaround this by using a file name with a manual numeric prefix, like so:

- File A: `0${SEG_NUM}` results in `01`, `02`, `03`
- File B: `1${SEG_NUM}` results in `11`, `12`, `13`
- File C: `2${SEG_NUM}` results in `21`, `22`, `23`

you can combine it with an appropriate `Minimum numeric padded length`

**Comment by vipergts** [comment]
Thank you for your commnet 

It was very helpful to me !

**Comment by KaShaunLeak** [comment]
@mifi I'd like a feature for SG_NUM offset as well. Using a prefix to SEG_NUM is an option, but in my use case, means I have to go back after the export and rename everything to match segment sequence.

Ex:
```
// day1-11.mp4 -> day-0${SEG_NUM}
day-001.mp4
day-002.mp4
day-003.mp4
...
day011.mp4


// day12-16.mp4 -> day-1${SEG_NUM}
day-101.mp4 // day 12
day-102.mp4 // day 13
day-103.mp4 // day 14
...
day-106.mp4 // day 15
```

I could programmatically go through after each export to fix the file names, but it'd be nice to specify an integer offset during export.

**Comment by mifi** [comment]
I've rewritten the template to allow javascript code, and a new variable `SEG_NUM_INT`, you can test it in the next nightly. example: `${SEG_NUM_INT+100}`

**Comment by discgrace** [comment]
@mifi Every time I try to use SEG_NUM_INT (or SEG_NUM_INT+xx), it comes up with "There is an error in the file name template: SEG_NUM_INT is not defined"
I used to use lossless cut a lot and had a naming string that would essentially start my clip names at the number +1 that my last clip ended at. EG, I would export say 20-30 clips from a video, numbered 1-30, and then the next video, I would do another batch of clips, and they would be named from 31 onwards
If I use ${SEG_NUM} the sequence is: 1, 2, 3, etc. if I use ${SEG_NUM-1} the sequence becomes 0, 1, 2, etc. however if I use ${SEG_NUM+1} the sequence becomes 11, 21, 31 etc, which honestly makes no sense to me, because I'd expect it to be 2, 3, 4 etc
please help!
