### ISSUE TITLE
No version number in the Windows Store version

### ISSUE THREAD

**Issue by SR--** [mifi/lossless-cut#1882]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

A small thing but in this version you cannot see the version info at all. Bought it to support the project. Great work!

![image](https://github.com/mifi/lossless-cut/assets/1008059/55218970-9690-44d1-bbf0-375fdd804e0c)

### Expected behavior

See the number

### Actual behavior

No number

### Share log

NA

**Comment by mifi** [comment]
thanks for your support! yea the MS store version initially showed the github version of losslesscut, but it confused some customers because the versioning scheme for the github releases is different from the MS Store versioning, so I removed it. I don't know how to access the MS Store app version from inside the app, but I will try to improve the dialog, thanks!

**Comment by mifi** [comment]
will look something like this in the next version:

<img width="271" alt="Screenshot 2024-02-07 at 22 28 56" src="https://github.com/mifi/lossless-cut/assets/402547/9579f1ed-4258-4763-a797-31871dd6c9ca">

**Comment by SR--** [comment]
That should do it, cheers.
________________________________

**Comment by SR--** [comment]
@mifi Is the MS Store version being updated OK? For me there is still no version number, and it has not been updated in ages, so I presume prior to 59 while here it is v61. Seems like I should just unistall the MS Store version and come back to this one?

**Comment by mifi** [comment]
There's only a single version on github that's not yet made it to the MS Store (v3.61.1). This version was released last week, so it needs more testing before being stable enough to release to the stores. If you want to test experimental new features, then feel free to install this version instead of the MS Store. If you want the most stable app then you should still stay on the MS Store version.
