### ISSUE TITLE
Better double click on segment

### ISSUE THREAD

**Issue by CatKasha** [mifi/lossless-cut#1923]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Currently if you double click on segment it will start playing at start frame of segment and this is fine, but it will keep playing until entire file ends
It will be better to stop playback at the end of segment to better understand how segment looks and how it will be exported

**Comment by mifi** [comment]
> Currently if you double click on segment it will start playing at start frame of segment and this is fine, but it will keep playing until entire file ends

Currently if you double click it will not start playing at all. it will just seek to the start frame of the segment, but it will not start playing. If it's already playing, then yes it will seek to the start frame while continue playing.

I'm not sure if changing the double click action to auto play until segment end, because every user is now used to the way it currently works.

I think for your use case you can instead achieve this by binding the keyboard action `togglePlayOnlyCurrentSegment`. then you can single-click a segment in the list and then press they keyboard button bound to `togglePlayOnlyCurrentSegment`.

**Comment by CatKasha** [comment]
Ah, there is key binding for this, thank you
