### ISSUE TITLE
possible bug? output video (MKV) is more than the selected range

### ISSUE THREAD

**Issue by mrjayviper** [mifi/lossless-cut#198]
So I have selected this range (00:50:40.462 to 01:16:10.040) and the resulting video goes past the selected range.

I did the same but using using ffmpeg directly using: ffmpeg -i input.mkv -ss 00:50:40.462 -to 01:16:10.040  -c:v copy -c:a copy "output.mkv"

and the video was cut at exactly the selected range.

Is this a bug in the app? Thanks

**Comment by tabby-jun** [comment]
If I am not wrong, lossless-cut by default cuts at the nearest keyframe.
You can read up on [keyframes here](https://en.wikipedia.org/wiki/Video_compression_picture_types)
*I'm not involved in any lossless-cut development* but this default was probably chosen because keyframes are generally the highest quality frames in compressed video formats.
You can choose to ignore this default when cutting, I think the option is in the lower right corner of the program.
And probably, If you choose to not cut by nearest keyframe, the resultant cut may not be fully lossless anymore.

**Comment by mrjayviper** [comment]
Thanks for the reply. I will check for that option you mentioned
