### ISSUE TITLE
Checkbox to export segments next to working file instead of specified directory

### ISSUE THREAD

**Issue by oxysoft** [mifi/lossless-cut#1980]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Couldn't find anything on this. I have to copy/paste the directory path every time because it remembers the export path for the last video. Would be much better for me with a toggle to ignore this export path and instead determine based on the working file.

**Comment by mifi** [comment]
exporting next to working file is the default behaviour unless
- you've set a working directory
- or: you're using mac os app store version, due to apple sandbox limitations

If yo uhave set a working directory, click the X in the top right to clear it: <img width="138" alt="Screenshot 2024-05-03 at 21 21 42" src="https://github.com/mifi/lossless-cut/assets/402547/86a60436-4db4-4fc2-96f7-4e8a1c0c3275">
