### ISSUE TITLE
Extracted audio track is shorter than expected unless video is played until the end before extraction

### ISSUE THREAD

**Issue by haminhtrifree** [mifi/lossless-cut#2052]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest) (also it might have already been fixed in latest [nightly build](https://github.com/mifi/lossless-cut#nightly-builds-))
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have a problem only with a particular file (or file type), [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)
- [X] Windows 7, 8 and 8.1 are [no longer supported](https://github.com/mifi/lossless-cut/discussions/1476). **This is not a question about Windows 8.1 or older.**

### Operating System

Windows 11

### Steps to reproduce

1. Load a video file into lossless cut (file size more than 1GB is better)
2. Click Tracks
3. Click 3 dots next to Audio track and export it as a separate file
4. Check the length of the exported audio track.

### Expected behavior

The audio track should have the same length as the original video file.

### Actual behavior

The length of the audio track is shorter than the length of the video file. This problem can be fixed if I preview the last seconds of the video. Then the exported audio file will have the same length.

**Comment by mifi** [comment]
how much shorter? sometimes a file can contain a video track and an audio track, and sometimes they do indeed have a different duration (e.g. the audio track ends before the video track, causing silence at the end of the video / or begining). in that case when you export the audio track to its own file, it will have the (shorter) length of the audio, because it's no longer constrained by the video's longer length.

> This problem can be fixed if I preview the last seconds of the video.

Are you 100% sure about this? I don't see how that can help because seeking the preview and extracting a track to a file are two completely unrelated systems (the latter is an ffmpeg command that gets run, you can see it in the "Last ffmpeg commands" page)
