### ISSUE TITLE
How to tell LC to auto-clean ALL *.log files at exit? and cache content?

### ISSUE THREAD

**Issue by tobwz** [mifi/lossless-cut#2058]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

As I found out LC writes a lot of stuff to *.log files (especially in "shared_proto_db" subfolder).
I *hate* leaving tracks on the hard disk.

How can I tell LC to automatically clean all such *.log files (and cache content) at LC exit?

if this is currently NOT possible:
Can this feature be added in the next release?

Thank you

**Comment by mifi** [comment]
I have no idea what is `shared_proto_db`. I don't even know which OS you are on. losslesscut should only write files into its appData folder.

see https://github.com/mifi/lossless-cut/blob/master/issues.md#faq (Where is application data, settings and temp files stored?)

so you should be able to delete that folder and the log will be gone too. If you have evidence that losslesscut writes files outside of that directory, then please elaborate.

note that losslesscut is **not** a portable app so it has to write temporary files and config to the appData folder in order to function properly, see also #645
I'm probably not going to change that, because most users would want their settings and app state to be remembered and not deleted every time the app closes.

If you want this behaviour you could write a wrapper script. something like this (assuming MacOS):

`losslesscut-wrapper.sh`
```bash
#!/bin/bash
/path/to/LosslessCut
rm -rf ~/'Library/Application Support/LosslessCut'
```

then `chmod +x losslesscut-wrapper.sh` and run this wrapper instead of LosslessCut directly

**Comment by tobwz** [comment]
> I have no idea what is `shared_proto_db`. I don't even know which OS you are on. losslesscut should only write files into its appData folder.

 `shared_proto_db` is a sub folder of LosslessCut Portable Apps.
 I am using LC on Windows 10

> so you should be able to delete that folder and the log will be gone too. 
> 
Yes, I can delete such files manually. The problem is that I have to do it manually.
LC should remove them automatically at exit to avoid leaving tracks.

> note that losslesscut is **not** a portable app 

What would you call:
https://portableapps.com/apps/music_video/lossless-cut-portable

>  so it has to write temporary files and config to the appData folder in order to function properly, see also #645 I'm probably not going to change that, because most users would want their settings and app state to be remembered and not deleted every time the app closes.

Yes, no problem. During running and processing LC can create as much files as it needs. 
I am asking for AUTOMATIC removal of unnecessary files at exit. And cache files are unnecessary beyond exit.
Keeping settings is welcomed. But not cache and log files.
> 
> If you want this behaviour you could write a wrapper script. something like this (assuming MacOS):
> 
> `losslesscut-wrapper.sh`
> 
> ```shell
> #!/bin/bash
> /path/to/LosslessCut
> rm -rf ~/'Library/Application Support/LosslessCut'
> ```
> 
> then `chmod +x losslesscut-wrapper.sh` and run this wrapper instead of LosslessCut directly

Yes, I can do that manually. But this feature should be a built-in part of LC.
It shouldn't be difficult to implement it.
