### ISSUE TITLE
Cannot change playback speed during FFMPEG assisted video playback

### ISSUE THREAD

**Issue by attilanyers** [mifi/lossless-cut#2124]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

Cannot change playback speed for H265 10 bit video. This is a very common format so it would be a good idea to support it.
Sample footage: https://drive.google.com/file/d/1RWxfEMQRXL_kM9tJsYXXvsC3XJOqPpay/view?usp=sharing

App says: "Unable to change playback rate right now"

**Comment by mifi** [comment]
Yes, this is a technical limitation. I don't think it will change any time soon unfortunately, because the ffmpeg assisted playback is a very cpu intensive operation, and increasing the playback rate would also greatly increase the cpu usage. you can work around this by pre-converting the file to a supported format, using one of the other choices (other than ffmpeg assisted playback).
