### ISSUE TITLE
Output format does not defaults to input format

### ISSUE THREAD

**Issue by kuzmandi** [mifi/lossless-cut#2129]
### Operating System

MacOS 13

### Steps to reproduce

If I input a .mp2 file, the output defaults to .mp3 instead of .mp2 (and fails, because it just work with .mp2 container)

### Expected behavior

It should be set automatically to the input format, in this case: .mp2

**Comment by mifi** [comment]
seems like a bug in ffmpeg/ffprobe where it detects mp2 files as mp3. will make a workaround

**Comment by Chariblaze** [comment]
I now have the opposite problem in LosslessCut 3.63.0 Windows.
Input mp3 file, detected output defaults to .mp2.
Test file: https://samplelib.com/sample-mp3.html

**Comment by mifi** [comment]
It seems that now the same file correctly resolves as mp3 without changes from 319124196e3ccb28c43ff9b1b4e5c5c9d0640312 - so it has probably been fixed in ffmpeg/ffprobe. I will revert 319124196e3ccb28c43ff9b1b4e5c5c9d0640312

tested with file from https://file-examples.com/index.php/sample-audio-files/sample-mp3-download/
