### ISSUE TITLE
'About program' window is not informative

### ISSUE THREAD

**Issue by toboil-features** [mifi/lossless-cut#2138]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

The window doesn't show current program version and link on Repo of GitHub. This is what it makes it uninformative.
![About LosslessCut](https://github.com/user-attachments/assets/619f35e2-6a91-470c-9696-c3bff8c6a5ca)

---

Expected template to be added:
```
Version: {Version}
Link: https://github.com/mifi/lossless-cut
Copyright © 2016-{Current-Year} Mikael Finstad
```
P.S. I want 2016 to be added to express the historical mean of the program.

**Comment by mifi** [comment]
i assume you're on linux? the about panel API in electron is very limited on Linux: https://github.com/electron/electron/issues/18918

i think i made a bug and that's why you're not seeing version. will fix that. I will update the copyright text like the following:

<img width="276" alt="Screenshot 2024-09-02 at 23 24 32" src="https://github.com/user-attachments/assets/54f02a26-faaa-4f57-973f-e9e9f99ea40e">

related #1537

**Comment by toboil-features** [comment]
Yes, I am under Linux. Thank you for improving it. 👍
