### ISSUE TITLE
"Unsupported file" when opening first time on Mac OS

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#215]
Only happens first time. Caused by this:

https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder

**Comment by niklaslovgren** [comment]
Seconded. Another thing that only seems to happen the first time is that the title on the main window showed "appName". When not opening for the first time, it correctly says "LosslessCut". The name of the app, as shown in dock and the top menu bar, showed "LosslessCut" all the time. Hope this is of any help, otherwise feel free to delete this post.

**Comment by mifi** [comment]
Have now fixed this in 72145c46fcc97a3047d0f097b1f75fdb0efd2d13
