### ISSUE TITLE
an explicit frame type indicator (or keyframe indicator)

### ISSUE THREAD

**Issue by kulkatt** [mifi/lossless-cut#2155]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

![image](https://github.com/user-attachments/assets/f8d36005-c2f3-4d09-9030-6e167efe3ba7)
as in avidemux, an explicit frame type indicator keeps the user acknowledged of whether the current frame is a keyframe, without zooming in the timeline or pressing frame-seeking keys repeatedly
very helpful in key-frame cutting mode

**Comment by mifi** [comment]
I tried to implement this, but unfortunately it doesn't work reliably. ffmpeg (and LosslessCut) are time-based, meaning they don't operate on frame numbers but on time values. When you seek one frame forward, it increments the time value by the approximate duration of a frame. For example a video with a fixed FPS (and btw some videos have variable fps) of 30fps, if you go to frame 1, you are at time 0.033333333... However due to this approximation and rounding errors, it means you may or may not be exactly positioned on the time value of they keyframe (or off by some offset), so we can reliably tell whether you are actually on a keyframe or not. We could do rounding to work around this, but it would not be accurate, especially for variable frame rate videos. It would give the user a false indication of (not) being on a keyframe. I think that unless we can get ffmpeg to work on frame numbers, there isn't any good way of doing this.

**Comment by kulkatt** [comment]
> I tried to implement this, but unfortunately it doesn't work reliably. ffmpeg (and LosslessCut) are time-based, meaning they don't operate on frame numbers but on time values. When you seek one frame forward, it increments the time value by the approximate duration of a frame. For example a video with a fixed FPS (and btw some videos have variable fps) of 30fps, if you go to frame 1, you are at time 0.033333333... However due to this approximation and rounding errors, it means you may or may not be exactly positioned on the time value of they keyframe (or off by some offset), so we can reliably tell whether you are actually on a keyframe or not. We could do rounding to work around this, but it would not be accurate, especially for variable frame rate videos. It would give the user a false indication of (not) being on a keyframe. I think that unless we can get ffmpeg to work on frame numbers, there isn't any good way of doing this.我尝试实现这个功能，但不幸的是它并不可靠。ffmpeg（和 LosslessCut）是基于时间的，这意味着它们不是基于帧号而是基于时间值。当你向前移动一帧时，它会将时间值增加一帧的近似时长。例如，一个固定 FPS（顺便说一下，有些视频的 FPS 是可变的）为 30fps 的视频，如果你跳到第 1 帧，则时间值为 0.033333333……然而，由于这种近似值和舍入误差，这意味着你可能或可能没有精确地定位在关键帧的时间值上（或偏离了某个偏移量），因此我们无法可靠地判断你是否真的在关键帧上。我们可以进行舍入来解决这个问题，但这并不准确，尤其是对于可变帧率的视频。这会给用户一个错误的指示，让他们误以为你不在关键帧上。我认为，除非我们能让 ffmpeg 处理帧号，否则没有什么好的方法可以做到这一点。

got it, 
then what about **a “Keyframe cut mode OK indicator”** which shows visually whether the current position is elegable for Keyframe cut mode output or not.
maybe in the form of a Green/Red light?
It will make the cutting process smoother by saving some extra press of ← → keys (prev/next keyframe) which is used to make sure it's sutable for Keyframe cut mode.

**Comment by mifi** [comment]
I will implement that. when approximately on a keyframe, the two keys will turn blue (instead of white)

<img width="142" height="34" alt="Image" src="https://github.com/user-attachments/assets/304de26c-69ae-424b-b57e-fa4d2707fd12" /> <img width="141" height="33" alt="Image" src="https://github.com/user-attachments/assets/9b6db036-7d06-47cd-b245-4eac68bc7716" />
