### ISSUE TITLE
Exported screenshots are PNG and not JPG on Linux

### ISSUE THREAD

**Issue by hotice** [mifi/lossless-cut#25]
On Linux, exporting a screenshot creates a file called ****.jpg, however, trying to open that with an image viewer file results in the following error: 
```
Error interpreting JPEG image file (Not a JPEG file: starts with 0x89 0x50)
```
After renaming the file from .JPG to .PNG, it works.

**Comment by mifi** [comment]
That's odd. Maybe electron for linux doesn't ship with JPEG support. I guess we could check the actual response from toDataURL('image/jpg') and save a file according to the actual format.
however `capture-frame` doesn't allow this

**Comment by mifi** [comment]
Actually it turns out that all images are exported as png but with jpg extension. I can only assume that most photo viewers don't care about the extension (instead they use magic number to identify type). But the viewer you are using is using the file extension.

I have now updated code to export jpg as intended. The method can now also easily support other formats in the future.

aee96f300b95f497f82e64c0e797bc186acf73a3
