### ISSUE TITLE
[Feature Request] Save as a "project file"

### ISSUE THREAD

**Issue by profucius** [mifi/lossless-cut#251]
An option to Save the current project as a file. Loading that file would restore the video file (referenced from original file location?) and the cut segments. Perhaps even restore settings such as the zoom level, mode, etc.

This would be useful for circumstances that you may want to make multiple edits of a file, or, if you need to go back and re-adjust an edit without starting all over. Or if you are in the middle of an edit, and need to reboot the machine, or have a power outage.

One step further, an option to auto-save as a project file with the same name as the video filename, in the same location as the original video file.

**Comment by mifi** [comment]
auto save/load of timestamps to CSV project file is now implemented in newest version along with many other new features!

**Comment by Github-Username-is-not-available** [comment]
> auto save/load of timestamps to CSV project file is now implemented in newest version along with many other new features!

But how do we know how it works? E.G. Where is the auto-save file located? How do we use it to restore a project? I think it would be good not to have taken the previous manual Save/Load feature away, as I've seen in videos on YouTube. Now I have no idea what's going on, or where files get saved to.

**Comment by mifi** [comment]
Project auto save is no longer stored as csv files. due to the limited nature of csv, we use .llc which is essentially a json file. Note that you can still manually export as csv from the file menu. Auto saved llc file is stored next to the input file (or if a working directory / output directory is set, it’s stored there). And it will be auto loaded when opening media in the same folder as the file

not sure which previous manual save/load featuee you’re talking about. You can still save/load projects (import/export)

**Comment by Github-Username-is-not-available** [comment]
OK thanks mifi. There's a YouTube video which shows it as "Save" & "Load", but now I understand that I'm supposed to use Import/Export with .llc files. Thanks a lot,
Rich
