### ISSUE TITLE
Feature request: Extract + convert audio only to like mp3 or wav

### ISSUE THREAD

**Issue by sIRwa2** [mifi/lossless-cut#306]
you are working hard on this tool! i love all the extras you bring. looking forward to the next release.

have a feature request: Extract + convert audio only to like mp3 or wav. 

If you dont like it thats fine :)

keep up the good work

**Comment by mifi** [comment]
Hi. You mean extract only audio from a video? I think you can do this already with "extract all streams" or Tracks selector? it will not convert to mp3 or wav but it will export its original codec from the video file. I might add some simple conversion to mp3 or wav too since converting is something that many people have requested.

**Comment by sIRwa2** [comment]
hi,Yes i am aware of the extract all streams function. but this gives me  m4a files that i need to process to an other format.. would be nice to have and export to mp3 feature..

**Comment by mifi** [comment]
Ok, this shouldn't be too hard to implement. I'll see when I have time

**Comment by mifi** [comment]
I put this task in other issue
