### ISSUE TITLE
volume control

### ISSUE THREAD

**Issue by taozi1996** [mifi/lossless-cut#307]
Now we need control system volume to adjust the software's volume.
Losslesscut can forbidden video's sound ,and can you make it possible to control the  volume by itself?

**Comment by mifi** [comment]
You mean in the preview or in the output?

**Comment by taozi1996** [comment]
> You mean in the preview or in the output?

in the preview

**Comment by mifi** [comment]
Why do you need that? Cant you use system volume?

**Comment by taozi1996** [comment]
> Why do you need that? Cant you use system volume?
I can use system volune.But sometimes I cut the videos with subtitle and I need use  potplayer to  browse videos.The volume of two  software need change frequently.

**Comment by wschlich** [comment]
The volume used by lossless-cut is MUCH too high, compared to mpv, vidcutter etc. It seems that it's overly amplified. This hurts my ears :(

**Comment by mifi** [comment]
That's strange. I'm not doing anything with the audio volume. Is it for files that are not natively supported?

**Comment by puttehi** [comment]
> That's strange. I'm not doing anything with the audio volume. Is it for files that are not natively supported?

99% of the files I cut are Nvidia Shadowplay captures so `.mp4`

The volume feels double to what it should be, it's VERY loud compared to any other software. Biggest gripe I have with LosslessCut is the missing volume slider. 
I don't really care for changing the output volume as I use LosslessCut just to cut fluff out of my clips for less filesize and do other work with other software but previewing/scrubbing clips is a pain when I have to keep adjusting my system volume which is perfectly set for my current audio setup and I'd rather not fiddle with it ever. This issue is highlighted when the amount of clips to cut grows.

**Comment by mifi** [comment]
now implemented volume control
