### ISSUE TITLE
Very incomplete French localisation

### ISSUE THREAD

**Issue by jdmuys** [mifi/lossless-cut#342]
Hi. I need a French version for my French family who doesn't understand English. The version available for download has a few French strings, but not enough. The help also would need a translation.

I am ready to help, and to provide the French translation, as well as some software development if necessary. But I would need some directions to get started. (I have no experience with Electron development)

As a first start I cloned the repo and tried to build and run. It failed. I will open a new issue for that.

I am on MacOS Catalina

**Comment by jdmuys** [comment]
I can now run LosslessCut from the source project.

I would love some pointer to start working on the localisation.

**Comment by mifi** [comment]
Hi. That's great! Localizations can be found here:
https://hosted.weblate.org/translate/losslesscut
It will automatically be pushed to this PR: #341
You can try to pull their fork if you want to see how the app looks with the translations:
https://github.com/weblate/lossless-cut/tree/weblate-losslesscut-losslesscut

**Comment by jdmuys** [comment]
I finished the translation of all 253 French strings. However, I have not tested yet: probably the end result is a bit awkward at the moment. I will fine tune shortly.

**Comment by trebmuh** [comment]
Hi @jdmuys and thanks.

I've looked at the 25 first translated strings and (I'm sorry if it hurts, but I have to say) I found several errors/mistakes in there. I've started to corrected those and will pursue on the next days.

When translating, you should stick to the original wording. Such as when it's written "_this file_", you shouldn't translate this to "_the video_". If upstream would have wanted to mean "_video_", they would have written "_video_", not "_file_".

A translation should always stick to the original meaning, unless there is a very very very good reason not to (in this case, it needs to be discussed and written somewhere). Especially when you are doing translation of a project where several people are likely to be working on it.

HTH

**Comment by jdmuys** [comment]
Hi, I am not surprised there are some mistakes as I finished late in the night and didn't have time to test. As I said, I don't consider this as a done job and will work on it until found satisfactory.

So I will comply with your requests, though I disagree mildly: IMHO, word by word translation rarely yields an idiomatic result. Regarding the translation of "file", the French "fichier" is very much a technical word. The layman will usually use "document" rather than "fichier" which is more a collection of "fiches" (≈cards). Though of course the technical meaning is leaking in the general use as well. I felt that "document" would be awkward for for a video file. I still believe that "vidéo" is a better translation of "file" when we are talking about a video file. 

Unfortunately, the "context" column in the translation tool is not used very effectively as it's just a repeat of the English string and doesn't give any additional context. IMHO, the context would be better if it did repeat the English string, but said where and how that string is used. This would be used in cases just as when the English word could be a noun or a verb or tensed verbal form for example.

All that said, you are the boss, and I will do as you asked.

**Comment by jdmuys** [comment]
In French there is actually no need for a space before a "?" or "!". I know there is some debate about that still (as there are in English as well for example with the Oxford coma), as it used to be the case a long time ago. But computers have changed that rule. I added the non breaking space for only one reason: the translation tool would not accept my translation without one.

I wanted to put a capital to start a phrase if the original had one. here too the context info would help. I probably made quite a few mistakes here due to the late hour. I will fix all those after testing.

I am going to try and test my translation today as per your instructions above.

**Comment by trebmuh** [comment]
Thanks for understanding.
I had times and check & fixed the 60 first strings.

A few considerations:

> So I will comply with your requests, though I disagree mildly: IMHO, word by word translation rarely yields an idiomatic result.

Unless there is a strong issue, this is the way to go. If a word needs to be change, as written above, it needs to be discussed and explained why. Keep in mind we're not translating a Shakespeare book here, but rather menu actions, and stuff like that. Most of the time there is no need to be creative.

> Regarding the translation of "file", the French "fichier" is very much a technical word

Well... everyone know what is a "fichier" ("file in English") in the informatics field since the 90s!

>  Though of course the technical meaning is leaking in the general use as well. I felt that "document" would be awkward for for a video file. I still believe that "vidéo" is a better translation of "file" when we are talking about a video file.

Then you have to talk to upstream to change this in the English root text, since:
- "file" :gb: translates to "fichier" :fr: 
- "document"  :gb:translates to "document" :fr: 
- "video" :gb: translates to "video" :fr: 
So, if upstream used "file", that means "file", not video or document.

Note that you might be fundamentally right here, but that is then totally out of the scope of a translation and would better to be discussed in upstream since if you were to be right on that one, then all the languages will benefit of it with updating this string, not only French.


> In French there is actually no need for a space before a "?" or "!".

AFAIK, yes, there is. See [here](https://www.lalanguefrancaise.com/general/les-regles-de-la-ponctuation-en-francais/) or [here](https://leconjugueur.lefigaro.fr/frponctuationtypographie.php) as 2 examples.

Hope all of that helps.

**Comment by trebmuh** [comment]
I've reviewed the 100 first strings now.
Will keep going.

**Comment by mifi** [comment]
Great! I just want to chime in to say that I have not added any context to each translation, that's why it's a bit hard to understand. The best thing you could do for now is search the source code for the exact string to see where it's being used. Also the reason why I'm using the word 'file' instead of 'video' is because in most cases we are talking about a video OR an audio file. Could also have used the word 'media', I suppose.

I will release a version with the translations as they are now. It's optional for people to enable other languages. Then we can release more versions later with more corrections.

**Comment by trebmuh** [comment]
I've reviewed the 180 first strings now.
Will keep going and should be finished tomorrow of all goes well.

**Comment by trebmuh** [comment]
I've finished the review. All seems good from my point of view now.

I've left 2 comments for 2 strings on weblate for you @mifi . Another general one is: is there a big difference when you're using "frame" and "image" in your texts?

**Comment by mifi** [comment]
Cool. I don't remember where I used frame now, but usually frame means video frame. I may not always have been 100% consistent on my usage of frame vs image.

I saw your comments, I've added a screenshot

**Comment by trebmuh** [comment]
OK. Thanks for your answer.
This thread can be closed now that the whole French translation has been done and reviewed.
