### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by MrTeeXD** [mifi/lossless-cut#355]
So, I am having trouble getting LosslessCut to run well on my Machine and for some reason, the timeline feels slow to work with and I feel a delay when I press the Play button even when my File is very low in size.

My Specs :
CPU : Intel i5-6400 2.70Ghz
GPU : Intel HD Graphics 530
RAM : 12GB DDR3 Dual Channel
OS : Windows 10 1909 64bit

**Comment by mifi** [comment]
Hi.

This is probably a limitation because your file is not natively supported by the preview player (maybe h265?), so LosslessCut is rendering a slow preview of your video, and it will unfortunately be a bit laggy. Actually it's an improvement over old versions though. In old versions you would only get 1-5 FPS preview on unsupported files.

Maybe I will be able to improve this, but as of now it's the best it can do

See also #88

**Comment by MrTeeXD** [comment]
Understood, thank your or your time
