### ISSUE TITLE
Feature request: export only a particular segment

### ISSUE THREAD

**Issue by bouscram** [mifi/lossless-cut#358]
Hi. After playing (a lot) with Lossless Cut, I think that the possibility to export only one segment would be nice (when you have defined many). It could be implemented with a right-click menu action, for instance?

**Comment by mifi** [comment]
Hi. Why do you need to have many segments but only export one?

**Comment by bouscram** [comment]
One case would be that you want to change the size or the cutting mode of only one of them. You can do the full export again, but it takes more time and you overwrite everything (unless you move the existing export).
I agree this is just a "nice to have" feature, but it seems quite natural to me (and I was almost surprised that it didn't exist, in fact...).

**Comment by Wiethoofd** [comment]
The overwrite shouldn't happen (anymore) iirc, the current unix timestamp in milliseconds will be added to the exported filename when you click `Export+merge`.

---
So as a current workaround after making multiple segments you could:

1. Save the project with all created segments as a CSV
2. Remove the unwanted segments from the _Segments to export_ list
3. Click `Export+merge` button to only export the single required segment
 3.1 Optionally rename the created file by clicking 'Show' to open the folder in your file manager
4. Load the previous project CSV from step 1 to restore list of previously created segments

---
As suggested by @bouscram adding the possibility for a 'right click action' to the _Segments to export_ would be nice.

Additionally more options in a menu with more export and playback options of single segments could be useful; to only output that single segment as a file, start from the exact in point and pause after playback, opening renaming dialog from the menu, removal or moving a segment up or down in the list etc.

**Comment by lacek** [comment]
> Hi. Why do you need to have many segments but only export one?

This would be very useful due reduce export time and disk writes when we need to adjust imprecise cutpoints.

Let say we need to extract 4 segments of in total 2GB from a video file of 3GB, we would have to export 4 times that take 40 seconds for 8GB in total.

If it there's an easy way (say 1 or 2 click instead of the complex process suggested by @Wiethoofd), we still have to export 4 times for adjusting the cutpoints but it takes only a quarter of time and disk write.

**Comment by mifi** [comment]
Have now implemented an export single button on the export summary page to only export the currently selected segment.

<img width="761" alt="Screenshot 2020-11-26 at 19 59 36" src="https://user-images.githubusercontent.com/402547/100385092-f2c54280-3021-11eb-9123-2c46c26a4304.png">


will be out in the nextv version

**Comment by markusd1984** [comment]
> Have now implemented an export single button on the export summary page to only export the currently selected segment.
> 
> <img alt="Screenshot 2020-11-26 at 19 59 36" width="761" src="https://user-images.githubusercontent.com/402547/100385092-f2c54280-3021-11eb-9123-2c46c26a4304.png">
> 
> will be out in the nextv version

@mifi Nice to have, I suggest though to change the wording to be more clear since "Segment" is the language used and more obvious to related to, e.g. "Export segment", "Export selected segment" , "export single segment",(or a segment # selection :D ).

Also Seeing that screen first time I was slightly surprised and unsure.... even forgot that these are buttons just like in the app (despite previously having been used to clicking buttons in the app). Perhaps change wording/include "Export...." "settings", "options" or "configuration". The fact it says "summary" lead me to think I only can click the blue buttons to confirm.

**Comment by mifi** [comment]
Gotcha. thanks for the feedback. I can change the title.

**Comment by KulaGGin** [comment]
> Hi. Why do you need to have many segments but only export one?

Create different videos from the same set of segments.
For example, I'd like to export: segment 1, 3 and 5 as a single video for video 1 and then segments 2, 4 and 6 for video 2. I could open 2 different project files I guess but that's a more complicated workflow and I'd like to have it in a single project.

**Comment by mifi** [comment]
@KulaGGin you can already enable/disable individual segments for export for a long time now
