### ISSUE TITLE
Crop video option

### ISSUE THREAD

**Issue by kashyap1113** [mifi/lossless-cut#38]
First I want to thank you for creating this awesome tool.
It would be nice, to have option to crop video.

**Comment by mifi** [comment]
Hi. I'm not sure how this would be possible to do with ffmpeg or even losslessly at all. Doing it in a lossy way would be outside the scope of this tool, I think.

**Comment by kashyap1113** [comment]
I think you are right. Cropping will need re-encoding, which is against the philosophy of this tool.

**Comment by tazztone** [comment]
avidemux can do lossless cutting and also re-encode with cropping

**Comment by mifi** [comment]
see #372

**Comment by ThreeDeeJay** [comment]
> Hi. I'm not sure how this would be possible to do with ffmpeg or even losslessly at all. Doing it in a lossy way would be outside the scope of this tool, I think.

> I think you are right. Cropping will need re-encoding, which is against the philosophy of this tool.

@mifi @kashyap1113 ffmpeg *can* crop losslessly using a bitstream flag like this:
```ffmpeg.exe -i "input.mp4" -c copy -bsf:v h264_metadata=crop_left=1920 "output.mkv"```
This would convert a 3D Side by Side video (3840x1080) to 2D (single view that's 1920x1080)
But very important to note (and would probably warrant a warning to the user): it won't actually delete the unused area from the file. 
It will just hide it so the size will remain basically the same as if both views were still visible, but I think all the flag does is to tell the *player* to crop the video on-the-fly. Useful to crop stuff for YouTube, which should delete the unused stuff (though I think YT keeps a copy of the original, but only used internally for re-encodes) so it's not a good idea to crop out sensitive data since the crop is reversible IIRC.
![image](https://github.com/mifi/lossless-cut/assets/71472458/1b2a65f8-7e66-4e32-a514-6a511f7ca2b7)
![image](https://github.com/mifi/lossless-cut/assets/71472458/9b05b061-3b9d-4d3e-888e-fe7fb7f53fd0)

**Comment by mifi** [comment]
@ThreeDeeJay thanks for your input. See #643

**Comment by ThreeDeeJay** [comment]
Woweee guess you guys are already way ahead of me lol 👌
