### ISSUE TITLE
MS Store Version hasn't been updated for a long time...

### ISSUE THREAD

**Issue by moleng09** [mifi/lossless-cut#415]
I see the snapcraft latest version is 3.22.3, but I'm still using 3.20.1...

**Comment by mifi** [comment]
It's correct that the Windows Store version is a few versions behind. There are some minor improvements that I haven't yet deployed in the Windows Store. The reason is that I haven't had the time to properly test the newest Windows version yet, and for the Windows Store version I want to be completely sure that it doesn't break anything. Once I'm confident that it's not buggy, I'll release it.

**Comment by mifi** [comment]
It's now up to date
