### ISSUE TITLE
failed to trash source file

### ISSUE THREAD

**Issue by svefro** [mifi/lossless-cut#426]
Deleting the source file seems to fail 50% off the time.
On windows you can not delete a file that is in use.
I know that is possible on linux and it might be on mac also.
Maybe there needs to be a delay before the actual file deletion after unloading the file from the player.

There should be a retry dialog if the file delete failed.

**Comment by happyfilmmaker** [comment]
I've experience similar issues, usually with longer files. Trashing file usually fails, but even the permanent delete dialog errors with "Error: EBUSY: resource busy or locked, unlink (file)". 

Process explorer on windows shows that Lossless Cut is still holding onto the file even after it refreshes to a fresh screen, and so the app needs to be closed in order to even delete the file manually.

**Comment by nim56** [comment]
I am having the same problem about 50% of the time, I have to close the app and manualy delete the file.

**Comment by mifi** [comment]
I think this is related to #272

**Comment by nim56** [comment]
Yes I am having the same problems as #272 on Windows 10

**Comment by mifi** [comment]
closing due to duplicate of that issue
