### ISSUE TITLE
Let LC remember window size and position on screen!

### ISSUE THREAD

**Issue by bsto** [mifi/lossless-cut#44]
Whenever I start LC the initial window is placed with a comparable small window and centered in the mid of the screen.

When I move and resized the window, then exit and restart it the previous window size + position is not remembered.

Could you make LC remember it in the next release?

Thank you

**Comment by mifi** [comment]
Hi. Isn't this something that the window manager can already handle? (Mac/Windows/X11)

**Comment by mifi** [comment]
Could look into https://github.com/mawie81/electron-window-state

**Comment by bsto** [comment]
Hmm, I am not talking about OTHER windows.
I am talking about its own, main window.

Current size and position is NOT remembered automatically by windows.

The program itself should take care and need to store it e.g. in registry or *.ini file.

Could you add this in the next release?

**Comment by mifi** [comment]
Why is this needed? Do you often close and restart LosslessCut?

**Comment by bsto** [comment]
Yes, I use my current,other video editor frequently multiple dozend times a week.

**Comment by mifi** [comment]
I wanna wait until this issue is solved: https://github.com/mawie81/electron-window-state/issues/4

**Comment by akovia** [comment]
Just chiming in from a Linux perspective. I have a dual monitor nVidia setup using twinview. Whenever I start this program, it always starts on my second screen. (my tv) I normally don't have that screen on unless I am actually watching something on my video player.

Most programs I use will launch it's window on the screen that my mouse is active on when launching. Other programs will launch it directly in the middle of both screens which isn't too bad as I can easily drag it where I need it because the window spans both monitors. This program seems to only launch onto my second (inactive) monitor no matter the circumstance.

I was being lazy and just r-clicking on the taskbar entry and selecting move to place it correctly, but I finally made a rule for gdevilspie to size and place it correctly every time now.

It's no big issue anymore, but something to consider if you do address window placement in Windows. A small tweak for Linux to either follow the mouse, or at least span both monitors as other programs do would be a nice addition. The first time I used this I think I launched it 3 times before I realized what was happening. lol

**Comment by mifi** [comment]
It seems to be fixed in the electron-window-state project now:
https://github.com/mawie81/electron-window-state/issues/4#issuecomment-441564412
I saw someone made an implementation in a fork.
https://github.com/PartyLich/lossless-cut/commit/1db760d802a9b1ccea0ae68e44854818ee34e8b9

**Comment by Shakil-Shahadat** [comment]
Any update on this issue?

**Comment by markusd1984** [comment]
If we were to have this it should only be via setting and not default, as the standard size provides a consistent experience and reasonable sized workspace for most people to start with and can resize or maximize in seconds when needed.

**Comment by mifi** [comment]
@markusd1984 is this really a problem? if the want to keep the default size, then they can just refrain from resizing it in the first place?

**Comment by markusd1984** [comment]
Not a problem, it's preference and convenience, although I think a low priority nice to have that @bsto seemed to have asked for. I think if anything it would be those users who prefer to have the app always open in full screen (i.e. to manage timeline better when zoomed in of larger videos) who would benefit and use this, me though doesn't bother to click maximize. 😄

**Comment by mifi** [comment]
Yea, but it's not only about fullscreen, it's also about openning on the same desktop as before, for people who have multi desktops.

But I'm still not 100% sure if this feature is something most people would like to have.

**Comment by Shakil-Shahadat** [comment]
Hey @markusd1984, what made you say that this should be a low priority?

In my 1080p monitor, LC looks very small. Guess what happens who uses 1440p or more resolution monitor, which is very common these days. And you wouldn't even notice anything if this gets implemented unless you resize your window and restart LC.

**Comment by markusd1984** [comment]
@Shakil-Shahadat it was just my opinion thinking the majority will use default size, I'm actually using 1080p where I can fit two LC windows side by side (to compare edit vs export) and comfortably cut segments etc.

I didn't think about larger resolutions, which is a good point you raised indeed, all for it. 👍

![image](https://user-images.githubusercontent.com/24621214/105868337-feb38d80-5fed-11eb-8032-2ad005fb869f.png)

**Comment by rubenalamina** [comment]
Any updates on this? I'd be really appreciated if the program can remember its window size and position. Either by default or with an option, but it would be a great QoL feature to have.
