### ISSUE TITLE
Preserve timestamp also for merged export files

### ISSUE THREAD

**Issue by adoenz** [mifi/lossless-cut#487]
Hi
Would it be possible to keep the timestamp preserved also when cut&merge exporting files?
The tool keeps the timestamp already when only cut->exporting but not when cut/merge/export.

I do a lot of slicing/merging of videos and want to keep the original timestamp.

**Comment by mifi** [comment]
Ah yes that would be nice indeed

**Comment by mifi** [comment]
implemented in 3.25.0

**Comment by adoenz** [comment]
Great job! Works like a charm, thanks!

**Comment by markusd1984** [comment]
@mifi what about an option to disable that? 
Traditional video editors always use current date/time for both the project file and video exports.

Otherwise, when editing videos days/weeks later, the exports may disappear down the list in folders with many files sorted by date/time, rather then chronologically expecting it to appear first as the newest (or at a later point in time find it by the date/time when one has edited the video).

**Comment by mifi** [comment]
Sure we could have an option to disable it, but I haven't heard anyone suggest it until now. feel free to open a feature request

**Comment by markusd1984** [comment]
@mifi thanks will do. Even when exporting the same segment multiple times with slight different beginning/ending it's a lot easier if files are sorted by creation date rather then file name. (I know the timestamp are included but creation date will always be superior among many files).

**Comment by markusd1984** [comment]
@mifi any chance we can add this in the next version please?

It's one of those convenient features where for a quick edits most people who use export folder in the same work dir as source file will probably notice when exporting a few times to make changes, that the files don't properly sort by creation date and appear mixed up, but probably won't complain or ask about this feature.

Really since this is actually abnormal behaviour compare to most apps in general, to preserve time stamp is actually and advanced feature for specific use case, e.g. lots of go pro or camera recordings where one just quickly wants to cut out some parts or split videos lossless and keep the original creation time among other source files, but not necessarily as much for editing the video to create a final video for upload. Thus this should not be the default behaviour but an opt in feature please.
