### ISSUE TITLE
Can't launch lossless-cut appimage with firejail 

### ISSUE THREAD

**Issue by arthurlogilab** [mifi/lossless-cut#499]
Trying to use https://github.com/netblue30/firejail with lossless-cut I can't launch it : 

``` 
firejail --appimage ./Downloads/LosslessCut-linux.AppImage
Mounting appimage type 2
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file

** Note: you can use --noprofile to disable default.profile **

Parent pid 241348, child pid 241351

**     Warning: dropping all Linux capabilities     **

Child process initialized in 106.03 ms

Parent is shutting down, bye...
```

No window appears. 

I can probably share the extended `--debug` output log if needed. 

cc @nchauvat

**Comment by mifi** [comment]
I have no idea how firejail works. someone needs to google this

**Comment by rusty-snake** [comment]
The problem is that there is no profile for it yet (but there's a request in netblue30/firejail#1139). Therefore the default.profile is used which is a compromise between security and compatibility. This may work, or maybe not, or only with some limitations. For electron apps it only works if it is started with `--no-sandbox`.

If you want to not use `--no-sandbox`, you should use electron.profile (e.g. `firejail --profile=electron --appimage ./Downloads/LosslessCut-linux.AppImage`). However you need to use firejail 0.9.64.2 or higher, the electron.profile in 0.9.64 and below does not work out-of-the-box and you need to use `--seccomp='!chroot'` (if unprivileged unerns are enabled) or `--ignore=nonewprivs --ignore=noroot --ignore=protocol --ignore=seccomp --ignore=caps.drop --caps.keep=sys_admin,sys_chroot` (if unprivileged unerns are disable) in addition. Moreover you can not use `--appimage` if unprivileged unerns are disabled and you start the electron-app w/o `--no-sandbox`.

**Comment by arthurlogilab** [comment]
@rusty-snake thanks for the follow up. I can confirm it working with 0.9.64 ... :tada:
