### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#5]
Auto update has been requested.
Or possibly download the  latest file when pressing the menu. This requires us to build into the binary which release link it should download. (Linux has multiple types)

**Comment by TechManiacHD** [comment]
Auto-update would be great but even a simple notification will do the job :)

**Comment by mifi** [comment]
a new version indicator in the top menu is now implemented in 5bf0c15d3e96e8a42d9d653c13b1342ea72abd92

**Comment by mifi** [comment]
Auto update should be alot simpler in new electron-builder
- https://github.com/electron-userland/electron-builder/blob/docs/encapsulated%20manual%20update%20via%20menu.js
- https://www.electron.build/auto-update

**Comment by mattack1** [comment]
Oops, I didn't look carefully enough.. Yeah, even if it "just" downloaded the disk image (e.g. the one that compares to how they got the app in the first place), that would be a HUUUGE improvement.

or at least make it clear that the menu item will bring you to the web site.

**Comment by mifi** [comment]
The app is now released on App Store and Microsoft Store which provide auto updates.

**Comment by mattack1** [comment]
It's $5 there.  Will there always be a free version too?  (manually downloadable)

One of the other issues mentions it too, but for me, I'm not even getting sound in seemingly normal mpeg 2 video. (Everything I get is downloaded from my TiVo).  The files open fine in standard quicktime player in the OS.  Just mentioning it here since I'm wondering if paying for it will help get these kinds of issues fixed faster.. because I think they're really related to the underlying ffmpeg?

**Comment by mifi** [comment]
Yes like I write in the readme it will always be free to manually download. Just that if people want to support me as well as have auto updates and hassle free installation they can but it there. Mpeg2 is an old codec so that may be why it’s not supported in chromium which is used by losslesscut. This could be solved if we compile a custom ffmpeg for chromium #88

It could also be solved by re-encoding the audio track for preview, but thAt could take a long time on long files, which defeats the purpose of losslesscut
