### ISSUE TITLE
Suggestion: Crop function

### ISSUE THREAD

**Issue by capekasa** [mifi/lossless-cut#504]
Great small program. I love it and use it often.
precise, quick. 

Please add a crop function! so resulting file will be smaller. Do not resize file, just crop.

**Comment by mifi** [comment]
hi. this is not possible to do losslessly. however it will be considered in a lossy version. see #372

**Comment by h-h-h-h** [comment]
@mifi:

Actually, this *is* possible with a Matroska container. I've done it multiple times in the past with MKVToolNix GUI, and it plays perfectly fine in MPC-BE. For not supporting players like VLC, bug reports should be filed.

The only caveat is that the video data stays the same and the file size is not reduced. But for playing purposes, it's very useful.

In MKVToolNix GUI, import a video file, click the video track, and hover over the text box of "Video properties > Cropping" for help. There's no visual cropping tool, though. That's why Lossless Cut should have it.

I wish this would be implemented. You'd just have to communicate that the feature is limited to MKV output, and that it's just the cropping information that is saved, so the file size isn't reduced and the player is responsible for the actual cropping.

If FFMPEG is the problem (can't it set metadata in the output file?), maybe *it* must be adapted or a multi-tool solution with the command line equivalent of the MKVToolNix GUI header editor might be the way to go.

**Comment by mifi** [comment]
Thanks for the input. I created a new issue #643
