### ISSUE TITLE
Auto delete '*-html5ified-dummy.mp4' files

### ISSUE THREAD

**Issue by Shakil-Shahadat** [mifi/lossless-cut#541]
- [x] I have tested the newest version
- [x] I have checked [readme](https://github.com/mifi/lossless-cut) and **Known issues** / **Troubleshooting**
- [x] I have searched for similar issues

The auto delete can be executed when the related file is closed or LC is closed.

Many people may want to keep that file, thus an option would be nicer.

**Comment by mifi** [comment]
Currently it will be deleted when you press the Trash source button #236

**Comment by Shakil-Shahadat** [comment]
Clicking on trash deletes both dummy file and source file. Don't wanna delete source file though.

**Comment by mifi** [comment]
Some people don't want to auto delete dummy. I will make a dialog when pressing trash source button:

<img width="532" alt="Screenshot 2020-12-14 at 16 15 37" src="https://user-images.githubusercontent.com/402547/102098975-152fcc00-3e28-11eb-8a7c-530d6c84ce40.png">

**Comment by Shakil-Shahadat** [comment]
Trash button working great so far. A couple of observations here.

1. The options in the dialogue box are not left-aligned like the image you posted, see mine.
![Capture](https://user-images.githubusercontent.com/8978625/102974616-08e2f780-4529-11eb-94a8-833a6e5e1d19.PNG)
1. The default option is a bit dangerous / intrusive. If anyone becomes a bit careless will delete the source file. I think the first option could be a safer default.
1. Button titles can be simplified and made more recognizable. I suggest renaming them to just 'Trash' & 'Cancel'.

**Comment by markusd1984** [comment]
@Shakil-Shahadat I agree, except the wording why not call it "Delete" instead of trash?
It seems rather odd, unless it's an american thing, delete is so more commonly used (just like in the second button "do not delete").

**Comment by mattack1** [comment]
Because at least according to the dialog, it is moving the files to the trash and NOT deleting them. i.e. the "garbage can" icon.. (I think Windows calls it recycling?)

this way, the user can manually recover them before emptying the trash.

**Comment by markusd1984** [comment]
Ah sry I mixed it up with previously deleting source file... Perhaps 'Move to recycle bin' would be better.

**Comment by mattack1** [comment]
But it's not called recycle on a Mac, that's what I meant.. so "Trash" is kind of generic.. unless you do different UI for different versions.. it would be trash on a mac.. (e.g. "Move to Trash" in the Finder).

**Comment by Shakil-Shahadat** [comment]
@markusd1984 Exactly as @mattack1 said.

Anyway, I sent two pr, if anyone can verify them, that would be nice. My build is not working on my machine.

**Comment by markusd1984** [comment]
@mattack1 gotcha, but then the second button should have been call Do not Trash 😃.

@Shakil-Shahadat @mifi Please let's also include an option to **clear all segments** as well, either in file menu or trash dialogue  #537.

**Comment by mifi** [comment]
@Shakil-Shahadat  thanks. I'm puzzled why the text is not left-aligned on your computer. Is it windows/linux?

**Comment by Shakil-Shahadat** [comment]
I'm on Windows 8.1.

**Comment by mifi** [comment]
@Shakil-Shahadat Thanks for reporting the alignment issue. for some reason the order of css is different in your build than mine.
I will fix it with `!important`
https://github.com/sweetalert2/sweetalert2/issues/1525

Oh and if you cannot build on windows, then please report an issue, I'm happy to assist.

@markusd1984 clear all segments is under edit menu already

**Comment by Shakil-Shahadat** [comment]
Everything is working fine.

I have managed to build but there were some warnings. I'll let you know when I test again.

Thank you so much.

**Comment by dandv** [comment]
I still see -html5ified-dummy.mkv files after exporting and closing LossLess cut. What are those files for?

I guess my expectation was to not see any temporary files in the source directory after I close the application. Maybe create them in $TMP? The `.csv` is somewhat intuitive (it's the project file, I guess), but the HTML5 file I haven't seen until now. Maybe because the video wasn't natively supported? Anyway, seems like a pretty technical detail to the casual user.

**Comment by Shakil-Shahadat** [comment]
@dandv You need to click the trash button to clean those files. They are needed to play video files.

**Comment by mattack1** [comment]
I really wish it would just put these files in /tmp or automatically delete them on quit (with a pref for that functionality I guess).

**Comment by mifi** [comment]
The dummy files are used in order to preview files that originally are not supported by the player.
The reason why these dummy files are not deleted is because they may take some time to generate. so if the user re-opens the same file later they shouldn't have to wait for that file to regenerate.
The reason why they are stored in the same place as output files, is that the may take a lot of space if the input video is large. Then it can overwhelm the primary hard drive of most computers (temp directory). I underrstand that many people edit videos on external drives, because they have more space there.
