### ISSUE TITLE
Feature Request: Advanced Merging (multiple codecs)

### ISSUE THREAD

**Issue by randoomx8** [mifi/lossless-cut#675]
**Is your feature request related to a problem? Please describe.**
Yes, this is related to an issue.
At the current time, attempting to merge two files with different codecs will result in data loss/corruption.

In my case (using some old family videos which I can not share) this issue manifests itself in the form of a 4-second-long frozen frame (while audio is still playing, so it de-syncs) at the start of a new video.

**Describe the solution you'd like**
I tried to re-create my issue with two public domain videos but found that the program is actually supposed to return an error asking you to upload videos of the same codec (It is actually the first time I have seen this message, previous attempts yielded no error messages).

Either way, I would like to have an option to upload videos of different codecs and merge them by re-encoding them first.
I attempted to do this myself with ffmpeg (and I can confirm this *should* be possible) but was unable to accomplish it.

**Describe alternatives you've considered**
As mentioned above, I tried to do it with ffmpeg (which I believe this program uses as a base).
Here are some sources I was able to find, although they provide no definitive answer:
https://video.stackexchange.com/questions/18247/ffmpeg-concat-demuxer-corrupted-output-freezed-video-on-some-concatenated-parts
https://stackoverflow.com/questions/56885303/ffmpeg-concat-demuxer-freezes-my-video-frames-while-joining-the-videos
https://stackoverflow.com/questions/37163256/ffmpeg-concat-video-and-audio-files

**Additional context**
I would really *really* like to be able to merge together those videos I got, please help me!

**Comment by mifi** [comment]
Hi. If you're unable to do it with ffmpeg directly, maybe you can try to use some GUI encoder like handbrake or similar (make sure you're using the exact same parameters for all videos). TBH if your goal is to re-encode videos in order to merge them, then I think losslesscut is not the right tool for the job, and it would be much better to use any normal video editor like iMovie, Shotcut etc, because it will be slower and you will lose quality no matter how you do it.
