### ISSUE TITLE
Merging audio tracks into one

### ISSUE THREAD

**Issue by Linnshet** [mifi/lossless-cut#689]
Hi,
So I just sat and wanted to show a gameplay clip to a friend, which I of course pull up my trusty LC to do. Thing is, I record gameplay audio and mic audio separately, in order to better mix and match in post. 

I noticed that I am able to remove tracks I don't want. However, I cannot merge the ones I do want into one file, for quick editing. So I will have to export each track as individual files (which takes forever), merge them together in Audacity (which is unnecessarily clunky), then import them into LC again to replace.

Wouldn't it just be lovely, to be able to click a button and it did all of that for me? I would think so. Hopefully a lot others would think so as well. :D

Love the app! Has saved me a ton of time in Resolve. Will definitely recommend to anyone who's interested in recording screen activity and gameplay. High regards,

**Comment by mifi** [comment]
Hi! I'm not sure what you want to do. Do you want to mix the audio signals together, or do you want to merge them as separate tracks in the same file (like multi-audio file)?

If you want to mix audio together, then unfortunately I don't think losslesscut will support it any time soon, because it's not lossless and outside the scope of the app. See #372

**Comment by mifi** [comment]
closing due to lack of response

**Comment by BBjen819** [comment]
Why is it closed.  Yes merging all audio tracks to one.

**Comment by mifi** [comment]
you want to mix them? this is not possible to do as a lossless operation so it's not really a losslesscut feature, but I've added it as a feature request in #372
