### ISSUE TITLE
Snap to nearest keyframe

### ISSUE THREAD

**Issue by Mixka** [mifi/lossless-cut#748]
It would be nice if the cursor will snap to the nearest keyframe.

Maybe add an option to always snap to the previous keyframe when the cut start point is assigned and next when the endpoint is assigned. Add buttons like:
- Set cut start from previous keyframe
- Set cut end to next keyframe

Also:
- Jump to previous keyframe
- Jump to next keyframe

**Comment by mifi** [comment]
Yes, the problem is that even if we snap to keyframe, ffmpeg will not always cut at that keyframe, but sometimes it will cut at the keyframe *before*. See discussions here; #546 - please continue discussion there

> Also:
> 
> * Jump to previous keyframe
> * Jump to next keyframe

There are already buttons like this:

<img width="101" alt="Screenshot 2021-07-25 at 14 25 10" src="https://user-images.githubusercontent.com/402547/126891225-0a8211e7-f3a5-4fa1-81d6-75961594b411.png">
