### ISSUE TITLE
添加一个声纹显示功能，以及快捷键放大缩小和剪辑和选择

### ISSUE THREAD

**Issue by xcd12138** [mifi/lossless-cut#766]
因为日常剪辑视频需要看到声音，因为有大量视频开头无声音，希望可以添加下，1这个声纹（声音的波纹Voiceprint）显示（可视化）的功能在blender也有，blender是开源软件，可以移植下。2放大和缩小对应的快捷键为[and]。3剪切的快捷键c。4选择的快捷键v，5虽然这软件本身已经很强大，如果添加我说的功能可以提高各位用户剪辑的效率

**Comment by mifi** [comment]
translated:

Because the daily editing video needs to see the sound, because there are a lot of videos with no sound at the beginning, I hope to add it. 1 This voiceprint (voiceprint of the sound) display (visualization) function is also available in Blender. Blender is an open source software and can be transplanted. . 2 The shortcut key corresponding to zoom in and zoom out is [and]. 3 Cut shortcut key c. 4 Select the shortcut key v, 5 Although the software itself is already very powerful, if you add the function I said, you can improve the efficiency of users editing

Hi. thanks for you suggestions. I believe these suggestions have already been covered by other issues, so I'm closing this.
