### ISSUE TITLE
misalignment

### ISSUE THREAD

**Issue by wicatfly** [mifi/lossless-cut#791]
Please fix this, I couldn't use Losslesscut normally
![捕获](https://user-images.githubusercontent.com/55010685/126874604-9a03949d-5239-48f2-bce1-e852ec3ec99e.JPG)

**Comment by mifi** [comment]
can you provide some more info? which version? did you try previous version? has it always been like this?

**Comment by wicatfly** [comment]
I used 3.36.0 on win 10. I haven't use another version. It hasn't always been like this, just from a week ago, I don't know what cause this. Thanks!

**Comment by mifi** [comment]
did you upgrade losslesscut when this happened? if not, then I think there is something wrong with your computer or operating system, because I have never seen this before. Please try on a different computer and see if it works. Or yo ucan try to delete AppData/Roaming/LosslessCut directory (please take a backup first. you will loose all settings)

**Comment by wicatfly** [comment]
Ok, thanks for helping!
2021年7月25日 +0800 13:44 Mikael Finstad ***@***.***>，写道：
