### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by xmha97** [mifi/lossless-cut#86]
Please create an installation for the app. (Windows)

**Comment by mifi** [comment]
I really don't want to do a lot of platform-specific scripts, so unless this is something that can be easily done with a few lines of script, i'm not going to prioritize unfortunately

**Comment by markusd1984** [comment]
Installers would be nice though as it makes it easy to have the app installed just like other apps where they are reachable via the start menu and optionally shortcut on the desktop, while the app resides in the common programmes location (possibly an update function could be the cherry on the cake 😁).

It also could make a rollout to multiple laptops easier and more important support an uninstall function.

If we ever find an easy way to add this to your automatic deployment that would be awesome. Similar to OBS and ShareX / Greenshot.

**Comment by mifi** [comment]
On Mac/Linux installers are not really preferred. On windows I know installers are used traditionally, but I believe that lately MS wants people to use the store instead due to safer and easier installation and auto updates. It’s possible to make an installer but I think (correct me if im wrong) it would require paying for a signing certificate, which I’m not going to do. I’m already paying for the store.

i think uninstall doesnt really provide much value because losslesscut is a self contained program that doesn’t install anything into the system, so the user can just delete the folder or exe.
