### ISSUE TITLE
Files fails merging if file name contains new line

### ISSUE THREAD

**Issue by slrslr** [mifi/lossless-cut#869]
LC 3.39.0
When i try to merge [these 2 files](https://ufile.io/zxat0049) ([mirror](https://mega.nz/file/Vl8gQTyK#dAkOujcwqLHCTBr8J2qdi9rZ3FmFd8hdtx-BBUEhGFo)) it fails.

Reason is kind of new-line in the file names.

Linux cli shows these files like this:
ls
''$'\n''-1.avi'  ''$'\n''-2.avi'

**Comment by mifi** [comment]
I dunno how to do make ffmpeg concat work with files with newline, I asked here: https://superuser.com/questions/1705808/ffmpeg-concat-escape-newline-character

**Comment by mifi** [comment]
superuser deleted my post, so i'm closing this because i cannot find out how to escape newline characters. my original (deleted) post for reference:

An example ffmpeg concat file looks like this:

```
file 'file:/path/to/file1.mp4'
file 'file:/path/to/file2.mp4'
```

I've already learned that if a file name includes the `'` character, it can be escaped successfully as `'\''`, like this:
```
file 'file:/path/to/file with quote'\''.mp4'`
```

However I cannot seem to find a way to escape the newline character `\n` for files that have newline in their name. Is this even possible with ffmpeg?

**Comment by slrslr** [comment]
@mifi I have just got an idea to send your question to AI ( https://chatgptfree.ai/ ) and it responded:

> Escaping newline characters in file names for use in ffmpeg concat files can be challenging. One approach to handle this is by using the octal representation of the newline character (\n) in the file path.
> 
> For example, if a file has a newline character in its name, you can represent the newline character as \012 in the file path. Here's an example of how you can include a file with a newline character in its name in an ffmpeg concat file:
> 
> bash
> file 'file:/path/to/file\nwithnewline\012.mp4'
> 
> By using the octal representation (\012) for the newline character in the file path, you can include files with newline characters in their names in an ffmpeg concat file.

**Comment by mifi** [comment]
Unfortunately that didn't work. I also tried replacing newline with the literal `\n`, which did not work either.
