### ISSUE TITLE
It is possible to only mute part of the audio on a video?

### ISSUE THREAD

**Issue by Levidant** [mifi/lossless-cut#90]
I known there's an option to mute the audio, but that still cut the video. So is there any option to only touch the audio, while the video is intact?

**Comment by mifi** [comment]
Why would you need this? Cut audio and leave video uncut? Or you mean cut audio and remove video?

**Comment by ccoenen** [comment]
Suggesting to close this. It is a question (not an issue) and the original poster did not follow up for more than three months.

**Comment by sasha2048** [comment]
I suppose, @Levidant meant [possibility to discard audio only of selected segments](https://github.com/mifi/lossless-cut/discussions/743). And that would be very useful feature, IMHO.

**Comment by mifi** [comment]
I don’t think there can be gaps in audio.

**Comment by honeestly** [comment]
You, mofo, are madafaking 1d10t!!! Not only is your work a total piece-o-C, users can't even preview a cut (since the cut out part is no matter still being played) until a product file is exported, which is not at all functional, but you fail to apprehend users needs even when they reach out to you explicitly. Fkin stupid dumbas cl)wn

**Comment by mifi** [comment]
how old are you?

**Comment by mifi** [comment]
I think this would have to be implemented in a way where audio is discarded for some segment, but then replaced with a generated silent audio track of the same length, with the same codec parameters as the original audio.

**Comment by mifi** [comment]
I think it's the same as #495
