### ISSUE TITLE
Debian 10, not able to open any mediafile, with error 'the media you tried to open does not exist'.

### ISSUE THREAD

**Issue by SMooxx** [mifi/lossless-cut#937]
In order to make it easier for me to help you, I ask that you please try these things first:
- Try with the newest version from GitHub: https://github.com/mifi/lossless-cut/releases/latest
- Check https://github.com/mifi/lossless-cut and **Known issues** / **Troubleshooting**
- Search for your problem under Issues or Discussions
- Please try other type of file and see if it works.

**Share information to help me understand**
- If you have an issue cutting a particular file, please also share the file, if possible. (or mail a link to finstaden@gmail.com if private.) Also please try to cut it with the ffmpeg command line directly.
- If you have a problem or an unexpected bug or crash, please open developer tools after starting LosslessCut and before doing the failing operation. Then share the output from the javascript Console. (Menu: Tools > Toggle Developer Tools)
- Please provide the error report if you got one (Menu: Help -> Report an error)

**Describe the bug**

losslesscut cant find any media files in my home folder and its sub-folders.
when I tryied to drag one mediafile (.mp4) into losslesscut, it says error as follows.
![image](https://user-images.githubusercontent.com/9960618/143536050-1964eabd-87fe-4399-9ab7-9fe5fca72223.png)

I installed losslesscut via snap store.

![image](https://user-images.githubusercontent.com/9960618/143537726-1f9d9ffa-4204-43ff-b3cf-7a52c7e0648f.png)

{
  "state": {
    "filePath": "",
    "externalStreamFiles": [],
    "mainStreams": [],
    "copyStreamIdsByFile": {},
    "cutSegments": [
      {}
    ],
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "linux",
  "version": "3.40.0"
}

**Comment by mifi** [comment]
Hi. Does it work with the non-snap version from github? Does it work with other versions? can you see if the ffmpeg path in the error message actually exists and try to run it from the command line?

**Comment by schwupp** [comment]
Same issue here. installed 3.42.0 via Ubuntu flathub. All files in home directory are not seen in open dialog or error message 'the media you tried to open does not exist' when drag/drop. If i move the file to i.e. ~/Downloads, it works perfectly.

**Comment by mifi** [comment]
Is this an issue only with snap/flathub or the same issue with version downloaded here from github?

**Comment by SMooxx** [comment]
Neither the LosslessCut-linux.AppImage file on github nor Snap/Flathub
store release can work for me.

Right now I can only use the LosslessCut application from the shell via
this link's bz2 file.
https://github.com/mifi/lossless-cut/issues/918#issuecomment-968288716

After unpack it into a location and make a **chrome-sandbox** sub-folder,
then launch it via the shell, it can work.
[image: image.png]

**Comment by mifi** [comment]
> losslesscut cant find any media files in my home folder and its sub-folders.
> when I tryied to drag one mediafile (.mp4) into losslesscut, it says error as follows.

This error message (`the media you tried to open does not exist`) in the first screenshot is caused by the [fs.access](https://nodejs.org/api/fs.html#fspromisesaccesspath-mode) method throwing an error. Meaning losslesscut either cannot find or doesn't have access the file. Could you check the developer tools for any error, as well as the path of the file that is being sent to losslesscut?

> I installed losslesscut via snap store.

also here if you could check if the file /snap/losslesscut/93/resources/ffmpeg exists?

> Neither the LosslessCut-linux.AppImage file on github nor Snap/Flathub

Same error for Image? (`the media you tried to open does not exist`)

**Comment by nekohayo** [comment]
The flathub flatpak package only sandboxes this app to the "Public", "Download" and "Videos" folders by default. I was encountering the same error, but by using [flat seal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) I was able to edit this app's permissions on my system, to add more folders (such as /tmp, or the area where my SD cards get mounted, etc.) to the allowed folders it can access.

That being said, I think the app should detect such situations and show more accurate and helpful error messages. "The file does not exist" is not entirely accurate from the user's point of view, it can rather be assumed that "Lossless Cut does not have permissions to access that file due to sandboxing" or something. It could try to inform the user of which directories the app has access to (if it can actually know that) or that tools like "flat seal" exist.

**Comment by mifi** [comment]
TBH I don't know how to differentiate between the case where the app is sandboxed and cannot access a file vs a file is not accessible because of lacking permissions, because afaik they will give the same error code from the operating system. However I agree that "the file does not exist" is not a very good error and should be improved.

**Comment by mifi** [comment]
have now improved the error so it should say that it doesn't have permission to open the file.
