### ISSUE TITLE
[Request] Allow Trimming in the middle of the video

### ISSUE THREAD

**Issue by chazzmichaels** [mifi/lossless-cut#98]
If this is possible, it would be a miracle.

**Comment by mifi** [comment]
What does this mean?

**Comment by BrianGitHubClough** [comment]
I really love lossles cut - I get in from a day's kayaking and and I can very quickly sort out my Go-Pro footage into lots of little clips. I can then concatenate them and produce a single long version - a movie.

However when I'm finished and I am watching the movie back and I often feel a have left one scene running a bit long. 
I can go back to the lossless cut short clip and readjust and reconcatenate and remake the movie but.....
It would be great if I could just snip out and discard those few seconds from the movie with a little program - you could call it lossles snip.

Lossles snip would do the opposite of lossless cut in that the selected edit would be lost rather than saved.

**Comment by reefhound** [comment]
This would be a great feature even if it was restricted to keyframes.

**Comment by mifi** [comment]
I think it’s the same as #7 being able to cut and discard/join?

**Comment by BrianGitHubClough** [comment]
I was thinking of something very simple in concept:
"Lossles snip would do the opposite of lossless cut in that the selected edit would be lost rather than saved."
But .... 
I do not know how it easy it would be to do

**Comment by mifi** [comment]
Now that we have a merge function implemented it should be possible to implement soemthing like this

**Comment by mifi** [comment]
I now implemented an auto merge function of multiple cut segments in 2.1.0, which should cover this use case. (Just cut all desired ranges except the portion you don't want and then toggle auto merge button)

**Comment by bjspi** [comment]
> I now implemented an auto merge function of multiple cut segments in 2.1.0, which should cover this use case. (Just cut all desired ranges except the portion you don't want and then toggle auto merge button)

Just stumbled across this Github Thread and found your answer. Sounds realy huge for me as well - I will check it out!
